### ISSUE TITLE
Weird error on exiting app

### ISSUE THREAD

**Issue by furryfaust** [robovm/robovm#1001]
```
AppLauncher failed with an exception:
org.robovm.libimobiledevice.LibIMobileDeviceException: IDEVICE_E_UNKNOWN_ERROR
        at org.robovm.libimobiledevice.IDevice.checkResult(IDevice.java:205)
        at org.robovm.libimobiledevice.IDeviceConnection.receive(IDeviceConnection.java:109)
        at org.robovm.libimobiledevice.util.AppLauncher.receiveGdbPacket(AppLauncher.java:450)
        at org.robovm.libimobiledevice.util.AppLauncher.receiveGdbPacket(AppLauncher.java:432)
        at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:786)
        at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:734)
        at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1052)
        at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)
```

**Comment by ntherning** [comment]
Please post on the RoboVM Google Group instead about your issue: groups.google.com/group/robovm
