### ISSUE TITLE
Missing a proper information message

### ISSUE THREAD

**Issue by TomGrill** [robovm/robovm#1012]
When I set the minimum OS version in the Info.plist.xml file like this:

```
<key>LSMinimumSystemVersion</key>
<string>7.0.0</string>
```

Now when i run the app on a device which OS version is older than i set above the app crashes with this stacktrace:
```
AppLauncher failed with an exception:
java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1058)
        at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)
Caused by: java.util.concurrent.TimeoutException
        at org.robovm.libimobiledevice.util.AppLauncher.receiveGdbPacket(AppLauncher.java:462)
        at org.robovm.libimobiledevice.util.AppLauncher.sendReceivePacket(AppLauncher.java:487)
        at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:778)
        at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:734)
        at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1052)
        ... 1 more

```

Took me a while to figure out what causes this exception. Maybe you can throw a nice message with the exception to make clear how to fix this.

Tested with iPhone 4;  OS 6.1.3, robovm 1.3, libgdx 1.6.3

**Comment by ldthai** [comment]
got same problem! did you found solution?
