### ISSUE TITLE
Linker error 1.3.1 snapshot

### ISSUE THREAD

**Issue by iitsoftware** [robovm/robovm#1013]
I'm getting this with 1.3.1 snapshot:

[ERROR] ld: in section __DATA,__datacoal_nt reloc 1: sectionForAddress(0x4C0) address not in any section file '/Users/am/.robovm/cache/ios/x86/release/Users/am/.robovm-sdks/robovm-1.3.1-SNAPSHOT/lib/robovm-rt.jar/com/android/okhttp/Address.class.o' for architecture i386
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/am/Development/explorer-ios/robovm-build/tmp/explorer/ios/x86/Main -arch i386 -Wl,-filelist,/Users/am/Development/explorer-ios/robovm-build/tmp/explorer/ios/x86/objects0 -L /Users/am/.robovm-sdks/robovm-1.3.1-SNAPSHOT/lib/vm/ios/x86 -ObjC -exported_symbols_list /Users/am/Development/explorer-ios/robovm-build/tmp/explorer/ios/x86/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -mios-simulator-version-min=8.0 -Wl,-no_pie -stdlib=libstdc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -lrobovm-bc -force_load /Users/am/.robovm-sdks/robovm-1.3.1-SNAPSHOT/lib/vm/ios/x86/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework MobileCoreServices -framework UIKit' failed (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:311)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:206)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:330)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:200)
	at org.robovm.compiler.Linker.link(Linker.java:423)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:400)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

**Comment by ntherning** [comment]
This has been fixed in 1.4.0 and later.
