### ISSUE TITLE
Treeshaker should include all parameter classes of a method when that method is called

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#1023]
Currently `NSString.getBoundingRect()` fails with a `ClassNotFoundException` if we `null` the `NSStringDrawingContext` parameter. The method has the `@WeaklyLinked` annotation.

It seems as if the treeshaker only includes parameter classes that have been directly referenced in user code. If we specify `null` and the class hasn't been used anywhere else, the treeshaker won't include it.

https://github.com/robovm/robovm/blob/master/cocoatouch/src/main/java/org/robovm/apple/foundation/NSString.java#L535

**Comment by BlueRiverInteractive** [comment]
Stacktrace of the error when you run the PhotoMap sample with aggressive treeshaker:

```Java
java.lang.ExceptionInInitializerError
	at org.robovm.apple.foundation.NSString.getBoundingRect(NSString.java:535)
	at org.robovm.samples.photomap.ui.LoadingStatus.<init>(LoadingStatus.java:51)
	at org.robovm.samples.photomap.ui.LoadingStatus.getDefaultLoadingStatus(LoadingStatus.java:39)
	at org.robovm.samples.photomap.ui.PhotoMapViewController.populateWorldWithAllPhotoAnnotations(PhotoMapViewController.java:233)
	at org.robovm.samples.photomap.ui.PhotoMapViewController.viewDidLoad(PhotoMapViewController.java:82)
	at org.robovm.samples.photomap.ui.PhotoMapViewController.$cb$viewDidLoad(PhotoMapViewController.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:369)
	at org.robovm.samples.photomap.PhotoMap.main(PhotoMap.java:35)
Caused by: java.lang.ClassNotFoundException: org.robovm.apple.uikit.NSStringDrawingContext
	at java.lang.VMClassLoader.findClassInClasspathForLoader(Native Method)
	at java.lang.PathClassLoader.findClass(PathClassLoader.java:193)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:515)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:475)
	at java.lang.reflect.Method.getParameterTypes(Native Method)
	at java.lang.reflect.Method.getParameterTypes(Method.java:474)
	at java.lang.reflect.Method.getParameterTypes(Method.java:470)
	at org.robovm.objc.ObjCRuntime.bind(ObjCRuntime.java:55)
	at org.robovm.apple.uikit.NSStringExtensions.<clinit>(NSStringExtensions.java:48)
	... 9 more
```
