### ISSUE TITLE
ClassCompiler fails to compile generic type method with a block

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#1027]
The following method crashes the ClassCompiler:
```Java
@Method(selector = "pinAllInBackground:block:")
public static native <T extends PFObject> void pinAllInBackground(NSArray<T> objects, @Block VoidBlock2<Boolean, NSError> block);
```
while this method works:
```Java
@Method(selector = "pinAllInBackground:")
public static native <T extends PFObject> BFTask pinAllInBackground(NSArray<T> objects);
```

It crashes with:
```Java
java.lang.RuntimeException: java.lang.reflect.GenericSignatureFormatError
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:299)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:305)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:388)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:448)
	at org.robovm.eclipse.internal.AppCompilerThread.doCompile(AppCompilerThread.java:60)
	at org.robovm.eclipse.internal.AppCompilerThread.run(AppCompilerThread.java:66)
Caused by: java.lang.reflect.GenericSignatureFormatError
	at org.robovm.compiler.util.generic.GenericSignatureParser.scanIdentifier(GenericSignatureParser.java:509)
	at org.robovm.compiler.util.generic.GenericSignatureParser.parseTypeVariableSignature(GenericSignatureParser.java:375)
	at org.robovm.compiler.util.generic.GenericSignatureParser.parseFieldTypeSignature(GenericSignatureParser.java:290)
	at org.robovm.compiler.util.generic.GenericSignatureParser.parseTypeSignature(GenericSignatureParser.java:394)
	at org.robovm.compiler.util.generic.GenericSignatureParser.parseMethodTypeSignature(GenericSignatureParser.java:412)
	at org.robovm.compiler.util.generic.GenericSignatureParser.parseForMethod(GenericSignatureParser.java:159)
	at org.robovm.compiler.util.generic.SootMethodType.getGenericParameterTypes(SootMethodType.java:48)
	at org.robovm.compiler.plugin.objc.ObjCBlockPlugin.transformMethod(ObjCBlockPlugin.java:174)
	at org.robovm.compiler.plugin.objc.ObjCBlockPlugin.beforeClass(ObjCBlockPlugin.java:146)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:678)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:291)
	... 5 more
```

**Comment by ntherning** [comment]
This is due to the fix for #977 which copies generic signatures to generated callback/bridge methods in `ObjCMemberPlugin`. The generated generic signature is invalid for this particular method and causes the `GenericSignatureFormatError` later on.
