### ISSUE TITLE
NoSuchMethodError in Box2D after using <treeShaker>agressive

### ISSUE THREAD

**Issue by cpalsulich** [robovm/robovm#1035]
The app crashes on startup. Here is the stack trace. The app works fine with the setting set to "conservative", but I'd definitely like to it to take up less space.

Versions: gdxVersion = '1.6.1' roboVMVersion = '1.4.0'

This is in dependencies under project(":ios")

    compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-ios"
This is in dependencies under project(":core")

    compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
Exception:

	java.lang.NoSuchMethodError: beginContact
		at com.badlogic.gdx.physics.box2d.World.newWorld(Native Method)
		at com.badlogic.gdx.physics.box2d.World.<init>(World.java)
		at com.cereal.stackking.worlds.GameWorld.<init>(GameWorld.java)
		at com.cereal.stackking.worlds.ArcadeWorld.<init>(ArcadeWorld.java)
		at com.cereal.stackking.screens.ArcadeScreen.startNewWorld(ArcadeScreen.java)
		at com.cereal.stackking.screens.ArcadeScreen.<init>(ArcadeScreen.java)
		at com.cereal.stackking.screens.MainMenuScreen.populateTable(MainMenuScreen.java)
		at com.cereal.stackking.screens.MainMenuScreen.<init>(MainMenuScreen.java)
		at com.cereal.stackking.Staq.load(Staq.java)
		at com.cereal.stackking.screens.SplashScreen.render(SplashScreen.java)
		at com.badlogic.gdx.Game.render(Game.java)
		at com.cereal.stackking.Staq.render(Staq.java)
		at com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java)
		at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java)
		at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$drawRect$(IOSGraphics.java)
		at org.robovm.apple.uikit.UIApplication.main(Native Method)
		at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
		at com.cereal.stackking.IOSLauncher.main(IOSLauncher.java)

I actually posted on StackOverflow also (http://stackoverflow.com/questions/31038634/nosuchmethoderror-in-box2d-after-using-treeshakeragressive-in-robovm), but I figured this would be better suited here.

**Comment by badlogic** [comment]
You can <forcelink> everything in the com.badlogic.gdx.physics.box2d
package in your robovm.xml. The reason this happens is because some Java
methods are only called from native code. RoboVM can't detect this. Please
file an issue with libGDX, we should force link a few packages so you don't
have to.

**Comment by cpalsulich** [comment]
After added <pattern>com.badlogic.gdx.physics.box2d.*</pattern> to <forceLinkClasses> the issue was resolved. Thanks for your help. I'll create the issue for libGDX.
