### ISSUE TITLE
Ignore classes/packages option

### ISSUE THREAD

**Issue by rjahn** [robovm/robovm#1055]
It would be nice to have a build option like forceLinkClasses which allows ignoring classes or packages. I had a problem with a library which had a class with something like this:

    public class JVxCalendarPane extends JPanel
    {  
      ... 
      public void addActionListener(ActionListener pActionListener) 
      {
          listenerList.add(ActionListener.class, pActionListener);
      }
    }

The listenerList is a field of JComponent, but not available in the phantom class. My build failed with this class. I removed the class from the jar and everything was fine, but a build option would be useful.

I didn't find an option in your documentation (http://docs.robovm.com/configuration.html).

**Comment by ntherning** [comment]
Please give more info on the error you got: http://docs.robovm.com/errors.html. A stacktrace from your IDE's log would be helpful. We've recently stumbled upon another issue related to phantom classes: #1061. This could be related.

**Comment by rjahn** [comment]
The whole output:

Issue 1
--------

  Requested project: /Entwicklung/sibvisions/jvxfxmobile/trunk/java/JVxGluonApp

  Stack trace:
    org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.2.1-bin.zip'.
    	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:57)
    	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
    	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:71)
    	at org.netbeans.gradle.project.tasks.AsyncGradleTask.runBuild(AsyncGradleTask.java:322)
    	at org.netbeans.gradle.project.tasks.AsyncGradleTask.doGradleTasksWithProgressIgnoreTaskDefCancel(AsyncGradleTask.java:427)
    	at org.netbeans.gradle.project.tasks.AsyncGradleTask.doGradleTasksWithProgressIgnoreTaskDefCancel(AsyncGradleTask.java:354)
    	at org.netbeans.gradle.project.tasks.AsyncGradleTask.doGradleTasksWithProgress(AsyncGradleTask.java:346)
    	at org.netbeans.gradle.project.tasks.AsyncGradleTask.access$400(AsyncGradleTask.java:76)
    	at org.netbeans.gradle.project.tasks.AsyncGradleTask$BuildExecutionItem$1.run(AsyncGradleTask.java:697)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager.runBlockingGradleTask(GradleDaemonManager.java:52)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$200(GradleDaemonManager.java:23)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:129)
    	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
    	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
    	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
    	at org.jtrim.concurrent.ThreadPoolTaskExecutor$ThreadPoolTaskExecutorImpl$QueuedItem.runTask(ThreadPoolTaskExecutor.java:1213)
    	at org.jtrim.concurrent.ThreadPoolTaskExecutor$ThreadPoolTaskExecutorImpl$Worker.executeTask(ThreadPoolTaskExecutor.java:1049)
    	at org.jtrim.concurrent.ThreadPoolTaskExecutor$ThreadPoolTaskExecutorImpl$Worker.run(ThreadPoolTaskExecutor.java:1179)
    	at org.jtrim.concurrent.ThreadPoolTaskExecutor$ThreadPoolTaskExecutorImpl$Worker$1.run(ThreadPoolTaskExecutor.java:998)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':launchIOSDevice'.
    	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:77)
    	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
    	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:108)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    	at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:43)
    	at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:30)
    	at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
    	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':launchIOSDevice'.
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    	... 32 more
    Caused by: soot.AbstractSootFieldRef$FieldResolutionFailedException: Class com.sibvisions.rad.ui.swing.ext.JVxCalendarPane doesn't have field listenerList : javax.swing.event.EventListenerList; failed to resolve in superclasses and interfacesLooking in com.sibvisions.rad.ui.swing.ext.JVxCalendarPane which has fields [<com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JSpinner years>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JSpinner months>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JSpinner currentTime>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JSpinner timeMinutes>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JSpinner timeSeconds>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JSpinner timeMinutes12>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JSpinner timeSeconds12>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JLabel spacer>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JLabel[] weekDays>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JLabel[] weeks>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.swing.JToggleButton[] days>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: java.util.GregorianCalendar calendar>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: java.util.Date date>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: java.lang.String actionCommand>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: javax.rad.util.TranslationMap translation>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: int selectedIndex>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: boolean ignoreEvent>, <com.sibvisions.rad.ui.swing.ext.JVxCalendarPane: boolean bTranslationEnabled>]
    Looking in javax.swing.event.ChangeListener which has fields []
    Looking in java.beans.PropertyChangeListener which has fields []
    Looking in java.awt.event.KeyListener which has fields []
    Looking in java.awt.event.MouseListener which has fields []
    Looking in java.awt.event.FocusListener which has fields []
    Looking in java.lang.Runnable which has fields []
    Looking in javax.rad.model.ui.ITranslatable which has fields []
    Looking in java.util.EventListener which has fields []
    Looking in javax.swing.JPanel which has fields []
    Looking in java.lang.Object which has fields []
    
    	at soot.AbstractSootFieldRef.resolve(AbstractSootFieldRef.java:116)
    	at soot.AbstractSootFieldRef.resolve(AbstractSootFieldRef.java:75)
    	at soot.jimple.internal.AbstractInstanceFieldRef.getField(AbstractInstanceFieldRef.java:89)
    	at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseAssignStmt(ConstraintCollector.java:725)
    	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:220)
    	at soot.jimple.toolkits.typing.integer.ConstraintCollector.collect(ConstraintCollector.java:48)
    	at soot.jimple.toolkits.typing.integer.TypeResolver.collect_constraints_1(TypeResolver.java:227)
    	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve_step_1(TypeResolver.java:180)
    	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve(TypeResolver.java:140)
    	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:143)
    	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:102)
    	at soot.BodyTransformer.transform(BodyTransformer.java:51)
    	at soot.Transform.apply(Transform.java:97)
    	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:66)
    	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
    	at soot.Pack.apply(Pack.java:117)
    	at soot.coffi.CoffiMethodSource.getBody(CoffiMethodSource.java:115)
    	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:87)
    	at soot.SootMethod.retrieveActiveBody(SootMethod.java:321)
    	at org.robovm.compiler.plugin.lambda.LambdaPlugin.transformMethod(LambdaPlugin.java:99)
    	at org.robovm.compiler.plugin.lambda.LambdaPlugin.beforeClass(LambdaPlugin.java:85)
    	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:678)
    	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:291)
    	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:305)
    	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:388)
    	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:448)
    	at org.robovm.compiler.AppCompiler$compile.call(Unknown Source)
    	at org.javafxports.jfxmobile.plugin.ios.task.BaseIosTask.compile(BaseIosTask.groovy:162)
    	at org.javafxports.jfxmobile.plugin.ios.task.IosDevice.iosDevice(IosDevice.groovy:36)
    	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    	... 55 more
