### ISSUE TITLE
LambdaPlugin can't deal with altMetafactory dynamic invokes that have ClassConstant as a marker interface

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#1081]
E.g. this [piece of code](https://github.com/gwtproject/gwt/blob/master/user/test-super/com/google/gwt/dev/jjs/super/com/google/gwt/dev/jjs/test/Java8Test.java#L713) will trigger:

```
java.lang.ClassCastException: soot.jimple.ClassConstant cannot be cast to soot.Type
	at org.robovm.compiler.plugin.lambda.LambdaPlugin.altMetafactory(LambdaPlugin.java:197)
	at org.robovm.compiler.plugin.lambda.LambdaPlugin.transformMethod(LambdaPlugin.java:119)
	at org.robovm.compiler.plugin.lambda.LambdaPlugin.beforeClass(LambdaPlugin.java:86)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:681)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:292)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:307)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:390)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:450)
	at org.robovm.eclipse.internal.AppCompilerThread.doCompile(AppCompilerThread.java:60)
	at org.robovm.eclipse.internal.AppCompilerThread.run(AppCompilerThread.java:66)
```

One of the marker interfaces passed to the dynamic invoked is of type `ClassConstant` and not `Type`.

**Comment by badlogic** [comment]
Closed in lambda branch.
