### ISSUE TITLE
RoboVM Studio plugin error on first start (fresh install)

### ISSUE THREAD

**Issue by n3o59hf** [robovm/robovm#1089]
![screenshot from 2015-07-24 12-42-03](https://cloud.githubusercontent.com/assets/408236/8871958/e88a7976-3201-11e5-8f3d-15ce73b72d55.png)

After restarting no RoboVM specific things are in new project creation wizard:
![screenshot from 2015-07-24 12-43-07](https://cloud.githubusercontent.com/assets/408236/8871979/15f1022c-3202-11e5-9402-d6fce28f7ac8.png)

Main exception seems to be
```
2015-07-24 12:40:36,395 [ 365496]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null [Plugin: org.robovm.intellij] 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null [Plugin: org.robovm.intellij]
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:177)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:377)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null [Plugin: org.robovm.intellij]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:245)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:39)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:601)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:621)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:388)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.init(ApplicationImpl.java:228)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:525)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:515)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
	... 16 more
Caused by: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null [Plugin: org.robovm.intellij]
	... 31 more
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null
	at com.intellij.openapi.projectRoots.impl.ProjectRootContainerImpl.addRoot(ProjectRootContainerImpl.java)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.addRoot(ProjectJdkImpl.java:368)
	at org.robovm.idea.sdk.RoboVmSdkType.setupSdkRoots(RoboVmSdkType.java:116)
	at org.robovm.idea.sdk.RoboVmSdkType$1.run(RoboVmSdkType.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1024)
	at org.robovm.idea.sdk.RoboVmSdkType.createSdkIfNotExists(RoboVmSdkType.java:136)
	at org.robovm.idea.RoboVmPlugin.extractSdk(RoboVmPlugin.java:229)
	at org.robovm.idea.components.RoboVmApplicationComponent.initComponent(RoboVmApplicationComponent.java:44)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:579)
	... 28 more
```
Log attached: 
http://pastebin.com/raw.php?i=i7pm9K9e

**Comment by badlogic** [comment]
This should be fixed in the latest nightly (available from http://download.robovm.org/nightlies/robovm-studio/robovm-studio-1.5.1-SNAPSHOT.dmg). Thanks for reporting!
