### ISSUE TITLE
Java IOException when compiling

### ISSUE THREAD

**Issue by cpalsulich** [robovm/robovm#1096]
Really the only thing of note that I changed was I switched from robovm bindings to robopods for Facebook, GPGS, and Flurry.

        compile "org.robovm:robopods-google-play-games-ios:1.5.1-SNAPSHOT"
        compile "org.robovm:robopods-facebook-ios:1.5.0"
        compile "org.robovm:robopods-flurry-ios:1.5.0"

Versions:

        gdxVersion = '1.6.1'
        roboVMVersion = '1.5.0'

Console Output:

	[INFO] Linking 3130 classes (ios x86_64 release)
	[DEBUG] 23103 methods out of 33673 included in the executable
	[DEBUG] Building executable /Users/chad/projects/stack-king/ios/robovm-build/tmp/Stack King/ios/x86_64/IOSLauncher
	[DEBUG] "2015-08-03 10:55:44.187 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	2015-08-03 10:55:44.191 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Backlight.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	2015-08-03 10:55:44.216 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	2015-08-03 10:55:44.224 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ATProperty.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -o "/Users/chad/projects/stack-king/ios/robovm-build/tmp/Stack King/ios/x86_64/IOSLauncher" -arch x86_64 "-Wl,-filelist,/Users/chad/projects/stack-king/ios/robovm-build/tmp/Stack King/ios/x86_64/objects0" -L /Users/chad/.robovm-sdks/robovm-1.5.0/lib/vm/ios/x86_64 -ObjC -Xlinker -alias_list -Xlinker "/Users/chad/projects/stack-king/ios/robovm-build/tmp/Stack King/ios/x86_64/aliased_symbols" -exported_symbols_list "/Users/chad/projects/stack-king/ios/robovm-build/tmp/Stack King/ios/x86_64/exported_symbols" -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-google-play-games-ios/1.5.1-SNAPSHOT/51273ef944f04279be23ae21de76b2f764d3cc78/robopods-google-play-games-ios-1.5.1-SNAPSHOT.jar.extracted/META-INF/robovm/ios/libs 
	[DEBUG]     -F/Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-bolts-ios/1.0.0-SNAPSHOT/7296ee3f895e3ec1632661ebcc1352732e0b2c1b/robopods-bolts-ios-1.0.0-SNAPSHOT.jar.extracted/META-INF/robovm/ios/libs -F/Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-google-plus-ios/1.5.1-SNAPSHOT/aa6ac15fc472c5819737d07e1f5858e172f196b8/robopods-google-plus-ios-1.5.1-SNAPSHOT.jar.extracted/META-INF/robovm/ios/libs -F/Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios/1.5.0/26317dc92ee9baabb8864afcd8e27f17f8938a71/robopods-facebook-ios-1.5.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/chad/projects/stack-king/ios/. -fPIC -mios-simulator-version-min=5.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -lrobovm-bc -force_load /Users/chad/.robovm-sdks/robovm-1.5.0/lib/vm/ios/x86_64/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework gpg -framework AddressBook -framework AssetsLibrary -framework CoreData -framework CoreLocation -framework CoreMotion -framework CoreTelephony -framework CoreText -framework MediaPlayer -framework QuartzCore -framework Security -framework SystemConfiguration -framework Bolts -framework AdSupport -framework CoreGraphics -framework StoreKit -framework GoogleOpenSource -framework GooglePlus -framework AudioToolbox -framework AVFoundation -framework MessageUI -framework FBSDKCoreKit -framework FBSDKLoginKit -framework FBSDKShareKit -framework FBSDKMessengerShareKit -framework FBAudienceNetwork -framework UIKit -framework OpenGLES -framework OpenAL -framework GameKit -weak_framework AdSupport -weak_framework StoreKit -lc++ -lz -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-flurry-ios/1.5.0/93c2e749ce62a9f6dd8c5e8a4f78bd869c74eb01/robopods-flurry-ios-1.5.0.jar.extracted/META-INF/robovm/ios/libs/libFlurry_6.6.0.a 
	[DEBUG]     -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-flurry-ios/1.5.0/93c2e749ce62a9f6dd8c5e8a4f78bd869c74eb01/robopods-flurry-ios-1.5.0.jar.extracted/META-INF/robovm/ios/libs/libFlurryAds_6.6.0.a -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-google-analytics-ios/1.5.0/9ad03cd6e70c9a10135b6d9b88547fd17112d152/robopods-google-analytics-ios-1.5.0.jar.extracted/META-INF/robovm/ios/libs/libGoogleAnalyticsServices.a -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-google-analytics-ios/1.5.0/9ad03cd6e70c9a10135b6d9b88547fd17112d152/robopods-google-analytics-ios-1.5.0.jar.extracted/META-INF/robovm/ios/libs/libAdIdAccess.a -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-google-analytics-ios/1.5.0/9ad03cd6e70c9a10135b6d9b88547fd17112d152/robopods-google-analytics-ios-1.5.0.jar.extracted/META-INF/robovm/ios/libs/libGGLAnalytics.a -lsqlite3 -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-google-apis-ios/1.0.0-SNAPSHOT/aa6aa87d4acc2b6108345307592a79f887938ffd/robopods-google-apis-ios-1.0.0-SNAPSHOT.jar.extracted/META-INF/robovm/ios/libs/libGGLCore.a -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d-platform/1.6.1/24a06691b8ff2d1944f3fc9e2264896d79baac28/gdx-box2d-platform-1.6.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx-box2d.a -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/projects/stack-king/libs/ios/admob-1.0.0.jar.extracted/META-INF/robovm/ios/libs/libadmob.a -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.6.1/2a62a7def04f4919c7962777c36ce540bdce820e/gdx-platform-1.6.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a 
	[DEBUG]     -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.6.1/2a62a7def04f4919c7962777c36ce540bdce820e/gdx-platform-1.6.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a -force_load /Users/chad/.robovm/cache/ios/x86_64/release/Users/chad/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.6.1/9ca5c641ba66b03119201918997138c21a5bb337/gdx-freetype-platform-1.6.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx-freetype.a -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks
	[ERROR] Couldn't compile app
	java.io.IOException: Cannot run program "2015-08-03 10:55:44.187 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	2015-08-03 10:55:44.191 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Backlight.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	2015-08-03 10:55:44.216 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	2015-08-03 10:55:44.224 xcodebuild[28738:1348457] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ATProperty.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++": error=63, File name too long
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
		at java.lang.Runtime.exec(Runtime.java:620)
		at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
		at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:246)
		at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:302)
		at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
		at org.robovm.compiler.util.Executor.exec(Executor.java:344)
		at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:367)
		at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:229)
		at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:341)
		at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:223)
		at org.robovm.compiler.Linker.link(Linker.java:424)
		at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:462)
		at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
		at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
	Caused by: java.io.IOException: error=63, File name too long
		at java.lang.UNIXProcess.forkAndExec(Native Method)
		at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
		at java.lang.ProcessImpl.start(ProcessImpl.java:134)
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
		... 14 more

**Comment by badlogic** [comment]
This appears to be an issue with Xcode plugins you installed, namely CocoaPods, Backlight, Auto-Importer and ATProperty. These plugins are likely outdated and need to be updated. Their Info.plists aren't containing UUIDs for the Xcode version you are currently using. If updating these plugins doesn't work, you can temporarily move them out of the plugins folder.

We'll try to find an automatic work-around for this, but the issue is with the plugins themselves.

**Comment by cpalsulich** [comment]
Thanks a lot for the update.
