### ISSUE TITLE
IDN.toASCII(String input) is broken

### ISSUE THREAD

**Issue by NoahAndrews** [robovm/robovm#1112]
I have been unsuccessful in finding a String (valid URL or otherwise) to pass to this function that won't cause it to emit this exception 
```java.lang.IllegalArgumentException: U_FILE_ACCESS_ERROR
	at libcore.icu.NativeIDN.convertImpl(Native Method)
	at libcore.icu.NativeIDN.convert(NativeIDN.java:39)
	at libcore.icu.NativeIDN.toASCII(NativeIDN.java:21)
	at java.net.IDN.toASCII(IDN.java:64)
	at java.net.IDN.toASCII(IDN.java:75)
	at com.mycompany.myapp.MyViewController.clicked(MyViewController.java:25)
	at com.mycompany.myapp.MyViewController.$cb$clicked(MyViewController.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:369)
	at com.mycompany.myapp.Main.main(Main.java:17)```

I discovered this issue because OkHttp was complaining about an invalid URL. I have successfully reproduced the issue in a new RoboVM project, and verified that the function accepts the same input when run in a normal Java console app.

**Comment by ntherning** [comment]
In order to use the `IDN` class you need a custom ICU data file. We haven't documented yet how to do that but please see this blog post and search for ICU: http://robovm.com/robovm-0-0-14-has-been-released/. Please post on the [Google Group](https://groups.google.com/group/robovm) if you need further help on this issue.
