### ISSUE TITLE
UICatalog sample throws ClassCastException when fetching UISplitViewController

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#1124]
```
java.lang.ClassCastException: org.robovm.apple.uikit.UIViewController cannot be cast to org.robovm.apple.uikit.UISplitViewController
	at org.robovm.samples.uicatalog.UICatalog.didFinishLaunching(UICatalog.java:35)
	at org.robovm.samples.uicatalog.UICatalog.$cb$application$didFinishLaunchingWithOptions$(UICatalog.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:369)
	at org.robovm.samples.uicatalog.UICatalog.main(UICatalog.java:49)
```

The marshaller can't find `UISplitViewController` in `ObjCClass.allNativeClasses` or `ObjCClass.allCustomClasses` and falls back to the super class `UIViewController`. When the `UICatalog` class then tries to cast the `UIViewController` to a `UISplitViewController` things explode.

**Comment by badlogic** [comment]
This has been fixed in a5f53da5f6b32acd440dcdd4e6fd7b81026452d1
