### ISSUE TITLE
RoboVM java.lang.IllegalArgumentException: unexpected url.

### ISSUE THREAD

**Issue by voidstarfire** [robovm/robovm#1153]
I'm using this excellent implementation of sockets using SocketIO Java client library:
https://github.com/socketio/socket.io-client-java

- Works on Desktop
- Works on Android
- Fails on iOS.  

You can download a working test example here
https://github.com/voidstarfire/LibGDX-SocketIO-with-Node/tree/master

This block creates an error.

```
//192.168.1.11:9999 OR https://192.168.1.11:9999
URI uri = new URI(ServerController.WEB_SERVER_API);  
socketIOClient = IO.socket(uri);
socketIOClient.on(Socket.EVENT_CONNECT, new Emitter.Listener()
```

I get the following error:

```
OLLY:LOG: Connecting with server: http://192.168.1.11:9999
java.lang.IllegalArgumentException: unexpected url: http://192.168.1.11:9999/socket.io/?EIO=3&sid=3x4xcfIDbrYeX7RlAAAH&transport=websocket
        at com.squareup.okhttp.Request$Builder.url(Request.java:153)
        at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:53)
        at io.socket.engineio.client.Transport$1.run(Transport.java:76)
        at io.socket.thread.EventThread.exec(EventThread.java:50)
        at io.socket.engineio.client.Transport.open(Transport.java:71)
        at io.socket.engineio.client.Socket.probe(Socket.java:459)
        at io.socket.engineio.client.Socket.onOpen(Socket.java:472)
        at io.socket.engineio.client.Socket.onHandshake(Socket.java:512)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:486)
        at io.socket.engineio.client.Socket.access$900(Socket.java:30)
        at io.socket.engineio.client.Socket$5.call(Socket.java:300)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:124)
        at io.socket.engineio.client.transports.Polling.access$700(Polling.java:16)
        at io.socket.engineio.client.transports.Polling$2.call(Polling.java:123)
        at io.socket.engineio.parser.Parser.decodePayload(Parser.java:255)
        at io.socket.engineio.client.transports.Polling._onData(Polling.java:133)
        at io.socket.engineio.client.transports.Polling.onData(Polling.java:105)
        at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
        at io.socket.thread.EventThread$2.run(EventThread.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:837)
```

**Comment by voidstarfire** [comment]
Any ideas? I tried debugging myself but I didn't get anywhere. Kinda stuck until this is resolved somehow :-!

**Comment by voidstarfire** [comment]
If anyone finds a fix for this I will personally transfer $XX into their account.
(Is that allowed here?)

**Comment by voidstarfire** [comment]
I'm still having this issue with RoboVM 1.8.0 & LibGDX 1.7.0

**Comment by voidstarfire** [comment]
PS I've tried with various URI's (http, ws, wss) etc. I've tried other socket libraries but they don't seem to work. Really stuck here on iOS, it needs to work with Socket.IO on node server :-/

**Comment by voidstarfire** [comment]
For anyone else stuck with this, it seems to be related to this:
https://github.com/robovm/robovm/issues/81

More info here on a fix potencial that's currently broken.
https://groups.google.com/forum/#!topic/robovm/m3XC_LdBVpU

**Comment by voidstarfire** [comment]
Can confirm that in RoboVM 1.9 this is fixed.
