### ISSUE TITLE
ViewController / Tapjoy memory crash and sample app

### ISSUE THREAD

**Issue by ericnondahl** [robovm/robovm#1163]
We've run into a crash seemingly related to low-level memory access in RoboVM and pushing view controllers. Related group discussion here: https://groups.google.com/forum/#!topic/robovm/wr3jAh7cca4

<pre>java.lang.IllegalStateException: The peer object type org.robovm.bindings.tapjoy.TJPlacement is not compatible with the expected type org.robovm.apple.foundation.NSMutableDictionary
at org.robovm.objc.ObjCObject.toObjCObject(ObjCObject.java)
at org.robovm.objc.ObjCObject.toObjCObject(ObjCObject.java)
at org.robovm.apple.foundation.NSObject$Marshaler.toObject(NSObject.java)
at org.robovm.apple.foundation.NSObject$Marshaler.toObject(NSObject.java)
at org.robovm.apple.foundation.NSMutableDictionary.$m$dictionaryWithContentsOfFile$(Native Method)
at org.robovm.apple.foundation.NSMutableDictionary.read(NSMutableDictionary.java)
at org.robovm.apple.foundation.NSMutableDictionary.read(NSMutableDictionary.java)
at com.badlogic.gdx.backends.iosrobovm.IOSApplication.getPreferences(IOSApplication.java)</pre>

<pre>java.lang.IllegalStateException: The peer object type Profile.ReferralCodeViewController is not compatible with the expected type Shared.PostDetailView.PostDetailViewController
    at org.robovm.objc.ObjCObject.toObjCObject(ObjCObject.java:302) 
    at org.robovm.objc.ObjCObject.toObjCObject(ObjCObject.java:249) 
    at org.robovm.objc.ObjCObject$ObjectOwnershipHelper.retain(ObjCObject.java:452) 
    at org.robovm.apple.uikit.UIStoryboard.$m$instantiateViewControllerWithIdentifier$(Native Method) 
    at org.robovm.apple.uikit.UIStoryboard.instantiateViewController(UIStoryboard.java) 
    at TableViewControllers.AnimatedTableViewController.loadDetailView(AnimatedTableViewController.java:545) 
    at TableViewControllers.AnimatedTableViewController.$cb$loadDetailView$(AnimatedTableViewController.java) 
    at org.robovm.apple.uikit.UIApplication.main(Native Method) 
    at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:384) 
    at com.chitter.chitter.MainChitter.main(MainChitter.java:300)
</pre>

I've made a sample app that includes the Tapjoy SDK which seems to be reliably reproducing this issue when pushing and popping the view controller.  Sample app repo here: https://github.com/ericnondahl/robovm-tapjoy-issue

To reproduce the issue:
1. Replace the `TAPJOY_SDK_KEY` in `RoboVMLauncher.java` with a tapjoy sdk key (your tapjoy dashboard configuration will also need a placement called "Offerwall"
2. Run the test app with RoboVM 1.7 and XCode 7 on an iOS device (I used an iPhone 6)
3. Press the button to open and close the tapjoy view controller several times and you will see a crash with no stack trace, or if you are lucky something like the stack trace above.

**Comment by ntherning** [comment]
Ok, I have tried to reproduce this using the latest nightly version of RoboVM to no avail. Did however run into another type of crash which was related to native memory. Had to fix the `TJPlacement` constructor to this:

```diff
diff --git a/robovm-memory-test/src/org/robovm/bindings/tapjoy/TJPlacement.java b/robovm-memory-test/src/org/robovm/bindings/tapjoy/TJPlacement.java
index fad5a08..54caec7 100644
--- a/robovm-memory-test/src/org/robovm/bindings/tapjoy/TJPlacement.java
+++ b/robovm-memory-test/src/org/robovm/bindings/tapjoy/TJPlacement.java
@@ -17,9 +17,9 @@ public class TJPlacement extends NSObject {
        @Method(selector = "placementWithName:delegate:")
        private static native @Pointer long fromNameDelegate(String name, TJPlacementDelegate delegate);

-   public TJPlacement(String name, TJPlacementDelegateAdapter delegate) {
-           super((SkipInit)null);
-           initObject(fromNameDelegate(name, delegate));
+ public TJPlacement(String name, TJPlacementDelegate delegate) {
+         super(fromNameDelegate(name, delegate));
+         retain(getHandle());
        }

        /**
```

The old code leaks a memory reference because of the call to `super((SkipInit)null)` and then doesn't retain the native reference properly. The last issue leads to a crash later on when RoboVM's ObjC bridge tries to release the reference during garbage collection. The native reference has already been deallocated on the native side.

With this fix and 1.8.1-SNAPSHOT I can tap 40+ times without any type of crash on my iPhone 6 in 32-bit and 64-bit mode. 

Also ran a Instruments run to make sure the added retain of `TJPlacement` instances doesn't leak such instances. Looks good. Screen shot below after 20 taps. As you can see there is a build up of other TapJoy related instances. Don't think those are RoboVM related though. There are no bindings for those classes in your project.

![screen shot 2015-10-01 at 11 58 26](https://cloud.githubusercontent.com/assets/135765/10218005/0530ce64-6834-11e5-939e-2568bc0d58d6.png)

Next I will try your original code with the 1.7 release and see if I can reproduce the actual issue you saw.

**Comment by ntherning** [comment]
Cannot trigger the `IllegalStateException` with RoboVM 1.7 either I'm afraid. Please try to apply the patch in the previous comment and rerun your app and see if that fixes the `IllegalStateException` you get.

**Comment by ericnondahl** [comment]
Looks like it was just that bad constructor on TJPlacement causing the memory issue. Can't reproduce the `IllegalStateException` after the constructor is fixed. Thanks a bunch for looking into this! I'll update my bindings for version 11 tapjoy in case other people try to use them.
