### ISSUE TITLE
Multiple out of Memory Exception/ GC Overhead limit Exceeded

### ISSUE THREAD

**Issue by divkala** [robovm/robovm#1178]
Hi,
 I understand this is the same issue as #1010, but I wasn't sure how to reopen the issue. I've left these comments on the page as well.  Feel free to close this issue and reopen #1010. 

I am trying to package my project for release on the app store. The Package for App Store works fine for 32 bit and 64 bit individually. However, while trying to packagee for All (32 bit + 64 bit), I am getting multiple OOME with GC overhead limit exceeded and I am unable to resolve.

I've udpated gradle.properties to have the following arguments: org.gradle.jvmargs=-Xms1024m -Xmx3072m -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC

I've also updatetd gradlew:
DEFAULT_JVM_OPTS="-Xm512m -Xmx3072m -XX:+UseConcMarkSweepGC -XX:-UseGCOverheadLimit"

(I had also changed eclipse.ini but reverted as it was to the same effect).
I've updated to Libgdx 1.7.0 and Robovm 1.8.0 but same results.

I am at a loss on how to proceed from here. Any help would be appreciated. 
Below is the error log data I could get my hands on.
Error Log Data: 
Message:
An internal error occurred during: "Package for App Store/Ad-Hoc distribution".

Stack Trace:
java.lang.OutOfMemoryError: GC overhead limit exceeded
at java.lang.reflect.Field.copy(Field.java:141)
at java.lang.reflect.ReflectAccess.copyField(ReflectAccess.java:140)
at sun.reflect.ReflectionFactory.copyField(ReflectionFactory.java:307)
at java.lang.Class.copyFields(Class.java:2882)
at java.lang.Class.getDeclaredFields(Class.java:1806)
at java.io.ObjectStreamClass.getDefaultSerialFields(ObjectStreamClass.java:1639)
at java.io.ObjectStreamClass.getSerialFields(ObjectStreamClass.java:1561)
at java.io.ObjectStreamClass.access$800(ObjectStreamClass.java:72)
at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:482)
at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:468)
at java.security.AccessController.doPrivileged(Native Method)
at java.io.ObjectStreamClass.(ObjectStreamClass.java:468)
at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:365)
at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:602)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
at org.robovm.compiler.clazz.Clazz.getClazzInfo(Clazz.java:82)
at org.robovm.compiler.ClassCompiler.mustCompile(ClassCompiler.java:241)
at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:242)
at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:326)
at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:386)
at org.robovm.compiler.AppCompiler.createIpa(AppCompiler.java:697)
at org.robovm.eclipse.internal.actions.CreateIPAAction$1$1.doCompile(CreateIPAAction.java:126)
at org.robovm.eclipse.internal.AppCompilerThread.run(AppCompilerThread.java:66)

P.S I tried creating a new libgdx default project (Red Screen with the LIbgdx sprite) with extensions Ashley AI Box2d and Freetype, the same which I am using in my project. The same error while trying to package it for app store.  

Any help in this regard would be much appreciated.

**Comment by divkala** [comment]
Okay. So I tried editing the eclipse.ini file again with values xms512 and xmx1024. This time it seems to have worked. Apologies for the post. Kindly close this as it is no longer an issue.
