### ISSUE TITLE
soot.RefType cannot be cast to soot.ArrayType

### ISSUE THREAD

**Issue by xespirit** [robovm/robovm#1181]
I am using robovm version 1.9.0, (robovm sdk 1.9.0, intellij idea plugin v. 1.9) and trying to build an app with mapDB library (compile "org.mapdb:mapdb:2.0-beta10")

Compilation fails with such exception:

```
[INFO] Compiling org.mapdb.BTreeMap (ios x86 release)
[ERROR] Couldn't compile app
java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
    at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseAssignStmt(ConstraintCollector.java:192)
    at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:220)
    at soot.jimple.toolkits.typing.integer.ConstraintCollector.collect(ConstraintCollector.java:48)
    at soot.jimple.toolkits.typing.integer.TypeResolver.collect_constraints_1(TypeResolver.java:227)
    at soot.jimple.toolkits.typing.integer.TypeResolver.resolve_step_1(TypeResolver.java:180)
    at soot.jimple.toolkits.typing.integer.TypeResolver.resolve(TypeResolver.java:140)
    at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:143)
    at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:102)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:97)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:66)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
    at soot.Pack.apply(Pack.java:117)
    at soot.coffi.CoffiMethodSource.getBody(CoffiMethodSource.java:115)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:87)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:321)
    at org.robovm.compiler.plugin.lambda.LambdaPlugin.transformMethod(LambdaPlugin.java:101)
    at org.robovm.compiler.plugin.lambda.LambdaPlugin.beforeClass(LambdaPlugin.java:89)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:700)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:303)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:308)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:391)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:451)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:768)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
```

**Comment by ntherning** [comment]
These are the problematic lines in `org.mapdb.BTreeMap`:

``` java
Object rootChild =
        (current<Integer.MAX_VALUE && q<Integer.MAX_VALUE) ?
        new int[]{(int)current,(int)q,0}:
        new long[]{current,q,0};
```

I can reproduce a similar problem with this method:

``` java
public static void main(String[] args) {
    Object o = args == null ? new int[] {0, 1}: new long[] {1, 0};
    System.out.println(o);
}
```

This gives:

```
java.lang.ClassCastException: org.robovm.compiler.llvm.PointerType cannot be cast to org.robovm.compiler.llvm.IntegerType
    at org.robovm.compiler.MethodCompiler.narrowFromI32Value(MethodCompiler.java:626)
    at org.robovm.compiler.MethodCompiler.assign(MethodCompiler.java:1161)
    at org.robovm.compiler.MethodCompiler.doCompile(MethodCompiler.java:403)
    at org.robovm.compiler.AbstractMethodCompiler.compile(AbstractMethodCompiler.java:77)
    at org.robovm.compiler.ClassCompiler.compileMethod(ClassCompiler.java:1426)
```

**Comment by badlogic** [comment]
Method Jimple without the `System.out`:

```
public static void main(java.lang.String[])
    {
        java.lang.String[] r0;
        java.io.Serializable r1, $r2;

     label0:
        r0 := @parameter0: java.lang.String[];
/*24*/
        if r0 != null goto label1;
/*24*/

        $r2 = newarray (int)[2];
/*25*/
        $r2[1] = 1;
/*25*/
        goto label2;
/*25*/

     label1:
        $r2 = newarray (long)[2];
/*26*/
        $r2[0] = 1L;
/*26*/

     label2:
        r1 = $r2;
/*24*/

     label3:
        return;
/*27*/

        localvar index=0 name=argv type=[Ljava/lang/String; start=label0 end=<end_of_method>;
        localvar index=1 name=o type=Ljava/lang/Object; start=label3 end=<end_of_method>;
    }
```

Byte code:

```
  // access flags 0x9
  public static main([Ljava/lang/String;)V
   L0
    LINENUMBER 24 L0
    ALOAD 0
    IFNONNULL L1
   L2
    LINENUMBER 25 L2
    ICONST_2
    NEWARRAY T_INT
    DUP
    ICONST_1
    ICONST_1
    IASTORE
    GOTO L3
   L1
    LINENUMBER 26 L1
   FRAME SAME
    ICONST_2
    NEWARRAY T_LONG
    DUP
    ICONST_0
    LCONST_1
    LASTORE
   L3
    LINENUMBER 24 L3
   FRAME SAME1 java/io/Serializable
    ASTORE 1
   L4
    LINENUMBER 27 L4
    RETURN
   L5
    LOCALVARIABLE argv [Ljava/lang/String; L0 L5 0
    LOCALVARIABLE o Ljava/lang/Object; L4 L5 1
    MAXSTACK = 5
    MAXLOCALS = 2
```

**Comment by badlogic** [comment]
It seems like the fix for issue #1 in line 229 of `MethodCompiler` is changing the Jimple, making it invalid. Output if you call `#toString()` on the method body in the debugger after that code block.

```
java.lang.RuntimeException: @param-assignment statements should precede all non-identity statements
\u0009at soot.jimple.JimpleBody.validateIdentityStatements(JimpleBody.java:101)
\u0009at soot.jimple.JimpleBody.validate(JimpleBody.java:67)
\u0009at soot.Printer.printTo(Printer.java:263)
\u0009at soot.Body.toString(Body.java:746)
\u0009at org.robovm.compiler.MethodCompiler.doCompile(MethodCompiler.java:234)
```

**Comment by badlogic** [comment]
This is what's confusing the method compiler into narrowing an 32-bit integer to a pointer type: `$r2[1] = 1;`

**Comment by ntherning** [comment]
Yes, `$r2` is shared by both code paths but shouldn't be. `LocalSplitter` should split this into two separate `Local`s. One with type `int[]` and one with type `long[]`.
