### ISSUE TITLE
AudioBuffer binding is not working

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1207]
When passing an (AudioBuffer *) from Obj-C to RoboVM AudioBuffer.AudioBufferPtr, when trying to use the AudioBuffer in it, a NullPointerException is thrown.

See a demo project here:

https://drive.google.com/file/d/0BwxZsZfwfINWYndDTWMyRXRmaDg/view?usp=sharing

This is the stack trace from a simulator run:

```
java.lang.NullPointerException
    at org.robovm.apple.coreaudio.AudioBuffer.setDataByteSize(AudioBuffer.java)
    at org.robovm.apple.coreaudio.AudioBuffer.setArrayData(AudioBuffer.java:79)
    at org.robovm.apple.coreaudio.AudioBuffer.setData(AudioBuffer.java:58)
    at com.mycompany.myapp.MyViewController.onFillBuffer(MyViewController.java:30)
    at com.mycompany.myapp.MyViewController.$cb$onFillBuffer$(MyViewController.java)
    at com.mycompany.myapp.AudioBufferLib.$m$callFillBuffer$(Native Method)
    at com.mycompany.myapp.AudioBufferLib.callFillBuffer(AudioBufferLib.java)
    at com.mycompany.myapp.MyViewController.clicked(MyViewController.java:20)
    at com.mycompany.myapp.MyViewController.$cb$clicked(MyViewController.java)
    at org.robovm.apple.uikit.UIApplication.main(Native Method)
    at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:395)
    at com.mycompany.myapp.Main.main(Main.java:17)
```

And this is from a run on a 64-bit device:

```
java.lang.NullPointerException
    at com.mycompany.myapp.MyViewController.onFillBuffer(MyViewController.java:29)
    at com.mycompany.myapp.MyViewController.$cb$onFillBuffer$(MyViewController.java)
    at com.mycompany.myapp.AudioBufferLib.$m$callFillBuffer$(Native Method)
    at com.mycompany.myapp.AudioBufferLib.callFillBuffer(AudioBufferLib.java)
    at com.mycompany.myapp.MyViewController.clicked(MyViewController.java:20)
    at com.mycompany.myapp.MyViewController.$cb$clicked(MyViewController.java)
    at org.robovm.apple.uikit.UIApplication.main(Native Method)
    at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:395)
    at com.mycompany.myapp.Main.main(Main.java:17)
```

@BlueRiverInteractive , can you please take a look?

**Comment by ntherning** [comment]
You only use `AudioBufferPtr` when the ObjC code uses `AudioBuffer **`.  Please try to use just `AudioBuffer` in Java instead.
