### ISSUE TITLE
IntelliJ plugin tries to run ios-sim on Windows

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#1216]
Based on the stacktrace it looks like the plugin tries to list the device types, but fails, because the program seems to not exist/be a valid Win32 application.

```
java.io.IOException: Cannot run program "C:\Users\Simon\.IdeaIC15\system\tmp\ios-sim1919157977012597298": CreateProcess error=193, %1 is not a valid Win32 application
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\Simon\.IdeaIC15\system\tmp\ios-sim1919157977012597298": CreateProcess error=193, %1 is not a valid Win32 application
    at org.robovm.compiler.target.ios.DeviceType.listDeviceTypes(DeviceType.java:135)
    at org.robovm.idea.RoboVmPlugin.setupRunConfigurations(RoboVmPlugin.java:588)
    at org.robovm.idea.components.RoboVmSdkUpdateComponent$3$1.run(RoboVmSdkUpdateComponent.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
    at org.robovm.idea.components.RoboVmSdkUpdateComponent$3.run(RoboVmSdkUpdateComponent.java:102)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: Cannot run program "C:\Users\Simon\.IdeaIC15\system\tmp\ios-sim1919157977012597298": CreateProcess error=193, %1 is not a valid Win32 application
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
    at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:246)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:302)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.execCapture(Executor.java:367)
    at org.robovm.compiler.target.ios.DeviceType.listDeviceTypes(DeviceType.java:101)
    ... 23 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
    at java.lang.ProcessImpl.start(ProcessImpl.java:137)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 30 more
```

**Comment by badlogic** [comment]
Fixed by not creating run configs on Windows.
