### ISSUE TITLE
Issue with extraneous xcrun output

### ISSUE THREAD

**Issue by kevin-vf** [robovm/robovm#1227]
When using 1.12.0 on my mac mini running OSX 10.11.2, the gradle launchIPhoneSimulator task when launched via IntelliJ IDEA doesn't work due to xcrun outputting extra warnings, possibly via stderr. I don't get the same behavior when I run xcrun (eg: xcrun --sdk iphonesimulator -f clang++) via a terminal, so I can't confirm if this is actually coming via stderr or not. Due to this if I run the gradle task via a terminal it runs properly as expected.

Looking at the old 1.8 source code, the issue might be due to org.robovm.compiler.util. Executor as used by org.robovm.compiler.util.ToolchainUtil::findXcodeCommand combining output from stdout and stderr.

The extra output is an extra line in the output before the tool path: "2016-01-14 09:59:43.449 xcodebuild[1222:31261]  ### Failed to load Addressbook class CNContactNameFormatter".

I've found that xamarin had a similar bug filed not too long ago: https://bugzilla.xamarin.com/show_bug.cgi?id=33576

Software Versions:
OSX: 10.11.2
IntelliJ IDEA: 15.0.2
RoboVM IntelliJ & Gradle plugins: 1.12.0

If you require any other info, please let me know.

The stacktrace (omitting org.gradle.api.tasks.TaskExecutionException):

```
Caused by: org.gradle.api.GradleException: Failed to launch simulator
    at org.robovm.gradle.tasks.AbstractSimulatorTask.launch(AbstractSimulatorTask.java:83)
    at org.robovm.gradle.tasks.IPadSimulatorTask.invoke(IPadSimulatorTask.java:28)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 70 more
Caused by: org.gradle.api.GradleException: Error building RoboVM executable for app
    at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:108)
    at org.robovm.gradle.tasks.AbstractSimulatorTask.launch(AbstractSimulatorTask.java:35)
    ... 79 more
Caused by: java.io.IOException: Cannot run program "2016-01-14 09:59:43.449 xcodebuild[1222:31261] ### Failed to load Addressbook class CNContactNameFormatter
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++": error=2, No such file or directory
    at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
    at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:246)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:302)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.exec(Executor.java:344)
    at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:405)
    at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:269)
    at org.robovm.compiler.target.ios.AppleDeviceTarget.doBuild(AppleDeviceTarget.java:543)
    at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:263)
    at org.robovm.compiler.Linker.link(Linker.java:423)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:465)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:780)
    at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:104)
    ... 80 more
Caused by: java.io.IOException: error=2, No such file or directory
    ... 93 more
```

**Comment by ntherning** [comment]
Thanks for reporting. This is a known issue. I'll keep it open until we fixed it.

**Comment by ntherning** [comment]
Fixed!
