### ISSUE TITLE
[ERROR] Couldn't start application - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fechy** [robovm/robovm#1230]
It happen the first time in running debug on a simulator.

``` java
[ERROR] Couldn't start application
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.robovm.compiler.target.ios.DeviceType.listDeviceTypes(DeviceType.java:124)
    at org.robovm.idea.running.RoboVmRunProfileState.customizeLaunchParameters(RoboVmRunProfileState.java:106)
    at org.robovm.idea.running.RoboVmRunProfileState.executeRun(RoboVmRunProfileState.java:49)
    at org.robovm.idea.running.RoboVmRunProfileState.startProcess(RoboVmRunProfileState.java:123)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
    at com.intellij.debugger.DefaultDebugEnvironment.createExecutionResult(DefaultDebugEnvironment.java:46)
    at com.intellij.debugger.engine.DebugProcessImpl.attachVirtualMachine(DebugProcessImpl.java:1907)
    at com.intellij.debugger.impl.DebuggerSession.attach(DebuggerSession.java:436)
    at com.intellij.debugger.impl.DebuggerSession.create(DebuggerSession.java:192)
    at com.intellij.debugger.impl.DebuggerManagerImpl.attachVirtualMachine(DebuggerManagerImpl.java:244)
    at org.robovm.idea.running.RoboVmRunner.attachVirtualMachine(RoboVmRunner.java:86)
    at org.robovm.idea.running.RoboVmRunner.doExecute(RoboVmRunner.java:70)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
    at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:376)
    at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:150)
    at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:343)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

The simulator is not previously open, and nothing happen after this error.
Following executions works as expected.

Seen on Macbook Pro (El Capitan) using IntelliJ IDEA 15.0.3. Using Robovm's latest Idea plugin (1.13.0) although it happens since several version before.

**Comment by ntherning** [comment]
Please run 

```
~/.robovm-sdks/robovm-1.13.0/bin/ios-sim showdevicetypes
```

and paste the output here.

**Comment by fechy** [comment]
Hi, here it is:

```
▶ ~/.robovm-sdks/robovm-1.13.0/bin/ios-sim showdevicetypes
Could not find service "com.apple.CoreSimulator.CoreSimulatorService" in domain for uid: 501
2016-01-28 10:18:18.102 ios-sim[5967:77307] launchctl print returned an error code: 28928
2016-01-28 10:18:18.102 ios-sim[5967:77307] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 7.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 7.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6s, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air-2, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Pro, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p, 9.1, (x86_64)
com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm, 2.1, (i386)
com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm, 2.1, (i386)
```

**Comment by ntherning** [comment]
Awesome! Now we know what to do to fix this.

In the meantime please try to run these commands to make the issue go away:

```
sudo chmod -R g-w $(xcode-select -p)/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc
sudo chown -R root:wheel $(xcode-select -p)/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc
```

After you run that rerun the `ios-sim showdevicetypes` command and make sure you don't see the 3 first lines you saw before. Let me know if that worked out for you.

**Comment by fechy** [comment]
Hi Niklas, 
Seems to work now. Here's the new output:

``` java
~/.robovm-sdks/robovm-1.13.0/bin/ios-sim showdevicetypes
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 7.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 7.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 7.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.1, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 8.1, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.3, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 8.3, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6s, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air-2, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Pro, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p, 9.1, (x86_64)
com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm, 2.1, (i386)
com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm, 2.1, (i386)
```

Running the debug task on a simulator now works perfectly.

Thanks for fixing!
