### ISSUE TITLE
Null Pointer while installing Haxm during initial install procedure for IntelliJ plugin.

### ISSUE THREAD

**Issue by dorkbox** [robovm/robovm#1231]
```
java.lang.NullPointerException
    at com.android.tools.idea.wizard.DialogWrapperHost.runSensitiveOperation(DialogWrapperHost.java:155)
    at org.robovm.idea.components.Haxm$SetupProgressStep.execute(Haxm.java:155)
    at com.android.tools.idea.welcome.wizard.ProgressStep$3.run(ProgressStep.java:93)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by badlogic** [comment]
What operating system?

**Comment by dorkbox** [comment]
Linux

**Comment by dorkbox** [comment]
specifically, xubuntu 15.10, x64 w/ Oracle JVM

**Comment by dorkbox** [comment]
Edit: fixed formatting in error message
