### ISSUE TITLE
Error when compiling in debug w/ Kotlin 1.0.0

### ISSUE THREAD

**Issue by deadpixelsociety** [robovm/robovm#1238]
When compiling my cross platform app using RoboVm 1.13 and Kotlin 1.0.0 in debug mode I receive the following in my RoboVM console:

```
[DEBUG] Couldn't resolve local var $i$f$toTypedArray in kotlin.reflect.jvm.internal.FunctionCaller$JvmStaticInObject call<kotlin.reflect.jvm.internal.FunctionCaller$JvmStaticInObject: java.lang.Object call(java.lang.Object[])>
[INFO] Compiling kotlin.reflect.jvm.internal.FunctionCaller$JvmStaticInObjectFieldGetter (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.FunctionCaller$JvmStaticInObjectFieldSetter (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.FunctionCaller$Method (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.FunctionCaller$StaticFieldGetter (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.FunctionCaller$StaticFieldSetter (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.FunctionCaller$StaticMethod (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$BuiltInFunction (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$BuiltInFunction$Predefined (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$JavaConstructor (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$JavaConstructor$asString$1 (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$JavaMethod (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$JavaMethod$asString$1 (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor (ios x86 debug)
[DEBUG] Couldn't find unit for local $i$f$substring:3 in scope of kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor:getConstructorDesc
search start unit: $r4 = r1
digraph {
   body [label="<div><pre>    public final java.lang.String getConstructorDesc()<br/>    {<br/>        kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor r0;<br/>        java.lang.String r1, $r2, $r4, $r6, $r7;<br/>        int i0;<br/>        java.lang.CharSequence $r3;<br/>        kotlin.TypeCastException $r5;<br/><br/>     label0:<br/>        r0 := @this: kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor;<br/>/*60*/<br/>        r1 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor: java.lang.String signature>;<br/>/*60*/<br/>/*60*/<br/>/*[not null]*/<br/>        $r2 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor: java.lang.String signature>;<br/>/*60*/<br/>/*[not null]*/<br/>        $r3 = (java.lang.CharSequence) $r2;<br/>/*60*/<br/>        i0 = staticinvoke <kotlin.text.StringsKt: int indexOf$default(java.lang.CharSequence,char,int,boolean,int,java.lang.Object)>($r3, 40, 0, 0, 6, null);<br/>/*60*/<br/>/*60*/<br/><br/>     label1:<br/>        $r4 = r1;<br/>/*252*/<br/>        if r1 != null goto label2;<br/>/*252*/<br/><br/>        $r5 = new kotlin.TypeCastException;<br/>/*252*/<br/>        specialinvoke $r5.<kotlin.TypeCastException: void <init>(java.lang.String)>(\"null cannot be cast to non-null type java.lang.String\");<br/>/*252*/<br/>/*[not null]*/<br/>        throw $r5;<br/>/*252*/<br/>/*[not null]*/<br/><br/>     label2:<br/>        $r6 = (java.lang.String) r1;<br/>/*252*/<br/>        $r7 = virtualinvoke $r6.<java.lang.String: java.lang.String substring(int)>(i0);<br/>/*252*/<br/>/*[not null]*/<br/>        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkExpressionValueIsNotNull(java.lang.Object,java.lang.String)>($r7, \"(this as java.lang.String).substring(startIndex)\");<br/>/*252*/<br/><br/>     label3:<br/>        return $r7;<br/>/*60*/<br/><br/>        localvar index=1 name=$receiver$iv type=Ljava/lang/String; start=label1 end=label3;<br/>        localvar index=2 name=startIndex$iv type=I start=label1 end=label3;<br/>        localvar index=3 name=$i$f$substring type=I start=label1 end=label3;<br/>        localvar index=0 name=this type=Lkotlin/reflect/jvm/internal/JvmFunctionSignature$KotlinConstructor; start=label0 end=<end_of_method>;<br/>    }<br/></pre></div>"]
   body -> stmt0   stmt0 [label="r0 := @this: kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor"];
   stmt1 [label="r1 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor: java.lang.String signature>"];
   stmt2 [label="$r2 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor: java.lang.String signature>"];
   stmt3 [label="$r3 = (java.lang.CharSequence) $r2"];
   stmt4 [label="i0 = staticinvoke <kotlin.text.StringsKt: int indexOf$default(java.lang.CharSequence,char,int,boolean,int,java.lang.Object)>($r3, 40, 0, 0, 6, null)"];
   stmt5 [label="$r4 = r1"];
   stmt6 [label="if r1 != null goto $r6 = (java.lang.String) r1"];
   stmt7 [label="$r5 = new kotlin.TypeCastException"];
   stmt8 [label="specialinvoke $r5.<kotlin.TypeCastException: void <init>(java.lang.String)>(\"null cannot be cast to non-null type java.lang.String\")"];
   stmt9 [label="throw $r5"];
   stmt10 [label="$r6 = (java.lang.String) r1"];
   stmt11 [label="$r7 = virtualinvoke $r6.<java.lang.String: java.lang.String substring(int)>(i0)"];
   stmt12 [label="staticinvoke <kotlin.jvm.internal.Intrinsics: void checkExpressionValueIsNotNull(java.lang.Object,java.lang.String)>($r7, \"(this as java.lang.String).substring(startIndex)\")"];
   stmt13 [label="return $r7"];
   stmt0 -> stmt1;
   stmt1 -> stmt2;
   stmt2 -> stmt3;
   stmt3 -> stmt4;
   stmt4 -> stmt5;
   stmt5 -> stmt6;
   stmt6 -> stmt7;
   stmt6 -> stmt10;
   stmt7 -> stmt8;
   stmt8 -> stmt9;
   stmt10 -> stmt11;
   stmt11 -> stmt12;
   stmt12 -> stmt13;
}

[DEBUG] Couldn't resolve local var $i$f$substring in kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor getConstructorDesc<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinConstructor: java.lang.String getConstructorDesc()>
[INFO] Compiling kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction (ios x86 debug)
[DEBUG] Couldn't find unit for local $i$f$substring:3 in scope of kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction:getMethodDesc
search start unit: $r4 = r1
digraph {
   body [label="<div><pre>    public final java.lang.String getMethodDesc()<br/>    {<br/>        kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction r0;<br/>        java.lang.String r1, $r2, $r4, $r6, $r7;<br/>        int i0;<br/>        java.lang.CharSequence $r3;<br/>        kotlin.TypeCastException $r5;<br/><br/>     label0:<br/>        r0 := @this: kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction;<br/>/*54*/<br/>        r1 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction: java.lang.String signature>;<br/>/*54*/<br/>/*54*/<br/>/*[not null]*/<br/>        $r2 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction: java.lang.String signature>;<br/>/*54*/<br/>/*[not null]*/<br/>        $r3 = (java.lang.CharSequence) $r2;<br/>/*54*/<br/>        i0 = staticinvoke <kotlin.text.StringsKt: int indexOf$default(java.lang.CharSequence,char,int,boolean,int,java.lang.Object)>($r3, 40, 0, 0, 6, null);<br/>/*54*/<br/>/*54*/<br/><br/>     label1:<br/>        $r4 = r1;<br/>/*252*/<br/>        if r1 != null goto label2;<br/>/*252*/<br/><br/>        $r5 = new kotlin.TypeCastException;<br/>/*252*/<br/>        specialinvoke $r5.<kotlin.TypeCastException: void <init>(java.lang.String)>(\"null cannot be cast to non-null type java.lang.String\");<br/>/*252*/<br/>/*[not null]*/<br/>        throw $r5;<br/>/*252*/<br/>/*[not null]*/<br/><br/>     label2:<br/>        $r6 = (java.lang.String) r1;<br/>/*252*/<br/>        $r7 = virtualinvoke $r6.<java.lang.String: java.lang.String substring(int)>(i0);<br/>/*252*/<br/>/*[not null]*/<br/>        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkExpressionValueIsNotNull(java.lang.Object,java.lang.String)>($r7, \"(this as java.lang.String).substring(startIndex)\");<br/>/*252*/<br/><br/>     label3:<br/>        return $r7;<br/>/*54*/<br/><br/>        localvar index=1 name=$receiver$iv type=Ljava/lang/String; start=label1 end=label3;<br/>        localvar index=2 name=startIndex$iv type=I start=label1 end=label3;<br/>        localvar index=3 name=$i$f$substring type=I start=label1 end=label3;<br/>        localvar index=0 name=this type=Lkotlin/reflect/jvm/internal/JvmFunctionSignature$KotlinFunction; start=label0 end=<end_of_method>;<br/>    }<br/></pre></div>"]
   body -> stmt0   stmt0 [label="r0 := @this: kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction"];
   stmt1 [label="r1 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction: java.lang.String signature>"];
   stmt2 [label="$r2 = r0.<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction: java.lang.String signature>"];
   stmt3 [label="$r3 = (java.lang.CharSequence) $r2"];
   stmt4 [label="i0 = staticinvoke <kotlin.text.StringsKt: int indexOf$default(java.lang.CharSequence,char,int,boolean,int,java.lang.Object)>($r3, 40, 0, 0, 6, null)"];
   stmt5 [label="$r4 = r1"];
   stmt6 [label="if r1 != null goto $r6 = (java.lang.String) r1"];
   stmt7 [label="$r5 = new kotlin.TypeCastException"];
   stmt8 [label="specialinvoke $r5.<kotlin.TypeCastException: void <init>(java.lang.String)>(\"null cannot be cast to non-null type java.lang.String\")"];
   stmt9 [label="throw $r5"];
   stmt10 [label="$r6 = (java.lang.String) r1"];
   stmt11 [label="$r7 = virtualinvoke $r6.<java.lang.String: java.lang.String substring(int)>(i0)"];
   stmt12 [label="staticinvoke <kotlin.jvm.internal.Intrinsics: void checkExpressionValueIsNotNull(java.lang.Object,java.lang.String)>($r7, \"(this as java.lang.String).substring(startIndex)\")"];
   stmt13 [label="return $r7"];
   stmt0 -> stmt1;
   stmt1 -> stmt2;
   stmt2 -> stmt3;
   stmt3 -> stmt4;
   stmt4 -> stmt5;
   stmt5 -> stmt6;
   stmt6 -> stmt7;
   stmt6 -> stmt10;
   stmt7 -> stmt8;
   stmt8 -> stmt9;
   stmt10 -> stmt11;
   stmt11 -> stmt12;
   stmt12 -> stmt13;
}

[DEBUG] Couldn't resolve local var $i$f$substring in kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction getMethodDesc<kotlin.reflect.jvm.internal.JvmFunctionSignature$KotlinFunction: java.lang.String getMethodDesc()>
[INFO] Compiling kotlin.reflect.jvm.internal.JvmPropertySignature (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmPropertySignature$JavaField (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.JvmPropertySignature$KotlinProperty (ios x86 debug)
[INFO] Compiling kotlin.reflect.jvm.internal.KCallableImpl$DefaultImpls (ios x86 debug)
[DEBUG] Couldn't find unit for local $i$a$1:3 in scope of kotlin.reflect.jvm.internal.KCallableImpl$DefaultImpls:call
search start unit: $r3 = interfaceinvoke r0.<kotlin.reflect.jvm.internal.KCallableImpl: kotlin.reflect.jvm.internal.FunctionCaller getCaller()>()
digraph {
   body [label="<div><pre>    public static transient java.lang.Object call(kotlin.reflect.jvm.internal.KCallableImpl, java.lang.Object[])<br/>    {<br/>        kotlin.reflect.jvm.internal.KCallableImpl r0;<br/>        java.lang.Object[] r1;<br/>        java.lang.IllegalAccessException r2, $r6;<br/>        kotlin.reflect.jvm.internal.FunctionCaller $r3;<br/>        java.lang.Object $r4, $r5;<br/>        kotlin.reflect.IllegalCallableAccessException $r7;<br/>        java.lang.Throwable $r8;<br/><br/>     label0:<br/>        r0 := @parameter0: kotlin.reflect.jvm.internal.KCallableImpl;<br/>/*65*/<br/>        r1 := @parameter1: java.lang.Object[];<br/>/*65*/<br/>        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkParameterIsNotNull(java.lang.Object,java.lang.String)>(r1, \"args\");<br/>/*65*/<br/><br/>     label1:<br/>        $r3 = interfaceinvoke r0.<kotlin.reflect.jvm.internal.KCallableImpl: kotlin.reflect.jvm.internal.FunctionCaller getCaller()>();<br/>/*65*/<br/>/*[unknown]*/<br/>        $r4 = virtualinvoke $r3.<kotlin.reflect.jvm.internal.FunctionCaller: java.lang.Object call(java.lang.Object[])>(r1);<br/>/*65*/<br/>/*[unknown]*/<br/>        $r5 = (java.lang.Object) $r4;<br/>/*65*/<br/>        return $r5;<br/>/*65*/<br/><br/>     label2:<br/>        $r6 := @caughtexception;<br/>/*65*/<br/><br/>     label3:<br/>        r2 = $r6;<br/>/*65*/<br/>        $r7 = new kotlin.reflect.IllegalCallableAccessException;<br/>/*141*/<br/>        specialinvoke $r7.<kotlin.reflect.IllegalCallableAccessException: void <init>(java.lang.IllegalAccessException)>(r2);<br/>/*141*/<br/>/*[not null]*/<br/>        $r8 = (java.lang.Throwable) $r7;<br/>/*141*/<br/>        throw $r8;<br/>/*141*/<br/>/*[not null]*/<br/><br/>        catch java.lang.IllegalAccessException from label1 to label2 with label2;<br/><br/>        localvar index=3 name=$i$a$1 type=I start=label1 end=label3;<br/>        localvar index=2 name=e$iv type=Ljava/lang/IllegalAccessException; start=label3 end=<end_of_method>;<br/>        localvar index=4 name=$i$f$reflectionCall type=I start=label1 end=<end_of_method>;<br/>        localvar index=0 name=$this type=Lkotlin/reflect/jvm/internal/KCallableImpl; start=label0 end=<end_of_method>;<br/>        localvar index=1 name=args type=[Ljava/lang/Object; start=label0 end=<end_of_method>;<br/>    }<br/></pre></div>"]
   body -> stmt0   stmt0 [label="r0 := @parameter0: kotlin.reflect.jvm.internal.KCallableImpl"];
   stmt1 [label="r1 := @parameter1: java.lang.Object[]"];
   stmt2 [label="staticinvoke <kotlin.jvm.internal.Intrinsics: void checkParameterIsNotNull(java.lang.Object,java.lang.String)>(r1, \"args\")"];
   stmt3 [label="$r3 = interfaceinvoke r0.<kotlin.reflect.jvm.internal.KCallableImpl: kotlin.reflect.jvm.internal.FunctionCaller getCaller()>()"];
   stmt4 [label="$r4 = virtualinvoke $r3.<kotlin.reflect.jvm.internal.FunctionCaller: java.lang.Object call(java.lang.Object[])>(r1)"];
   stmt5 [label="$r5 = (java.lang.Object) $r4"];
   stmt6 [label="return $r5"];
   stmt7 [label="$r6 := @caughtexception"];
   stmt8 [label="r2 = $r6"];
   stmt9 [label="$r7 = new kotlin.reflect.IllegalCallableAccessException"];
   stmt10 [label="specialinvoke $r7.<kotlin.reflect.IllegalCallableAccessException: void <init>(java.lang.IllegalAccessException)>(r2)"];
   stmt11 [label="$r8 = (java.lang.Throwable) $r7"];
   stmt12 [label="throw $r8"];
   stmt0 -> stmt1;
   stmt1 -> stmt2;
   stmt2 -> stmt3;
   stmt2 -> stmt7;
   stmt3 -> stmt4;
   stmt3 -> stmt7;
   stmt4 -> stmt5;
   stmt4 -> stmt7;
   stmt5 -> stmt6;
   stmt5 -> stmt7;
   stmt6 -> stmt7;
   stmt7 -> stmt8;
   stmt8 -> stmt9;
   stmt9 -> stmt10;
   stmt10 -> stmt11;
   stmt11 -> stmt12;
}

[DEBUG] Couldn't resolve local var $i$a$1 in kotlin.reflect.jvm.internal.KCallableImpl$DefaultImpls call<kotlin.reflect.jvm.internal.KCallableImpl$DefaultImpls: java.lang.Object call(kotlin.reflect.jvm.internal.KCallableImpl,java.lang.Object[])>
[DEBUG] Couldn't find unit for local $i$f$reflectionCall:4 in scope of kotlin.reflect.jvm.internal.KCallableImpl$DefaultImpls:call
search start unit: $r3 = interfaceinvoke r0.<kotlin.reflect.jvm.internal.KCallableImpl: kotlin.reflect.jvm.internal.FunctionCaller getCaller()>()
digraph {
   body [label="<div><pre>    public static transient java.lang.Object call(kotlin.reflect.jvm.internal.KCallableImpl, java.lang.Object[])<br/>    {<br/>        kotlin.reflect.jvm.internal.KCallableImpl r0;<br/>        java.lang.Object[] r1;<br/>        java.lang.IllegalAccessException r2, $r6;<br/>        kotlin.reflect.jvm.internal.FunctionCaller $r3;<br/>        java.lang.Object $r4, $r5;<br/>        kotlin.reflect.IllegalCallableAccessException $r7;<br/>        java.lang.Throwable $r8;<br/><br/>     label0:<br/>        r0 := @parameter0: kotlin.reflect.jvm.internal.KCallableImpl;<br/>/*65*/<br/>        r1 := @parameter1: java.lang.Object[];<br/>/*65*/<br/>        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkParameterIsNotNull(java.lang.Object,java.lang.String)>(r1, \"args\");<br/>/*65*/<br/><br/>     label1:<br/>        $r3 = interfaceinvoke r0.<kotlin.reflect.jvm.internal.KCallableImpl: kotlin.reflect.jvm.internal.FunctionCaller getCaller()>();<br/>/*65*/<br/>/*[unknown]*/<br/>        $r4 = virtualinvoke $r3.<kotlin.reflect.jvm.internal.FunctionCaller: java.lang.Object call(java.lang.Object[])>(r1);<br/>/*65*/<br/>/*[unknown]*/<br/>        $r5 = (java.lang.Object) $r4;<br/>/*65*/<br/>        return $r5;<br/>/*65*/<br/><br/>     label2:<br/>        $r6 := @caughtexception;<br/>/*65*/<br/><br/>     label3:<br/>        r2 = $r6;<br/>/*65*/<br/>        $r7 = new kotlin.reflect.IllegalCallableAccessException;<br/>/*141*/<br/>        specialinvoke $r7.<kotlin.reflect.IllegalCallableAccessException: void <init>(java.lang.IllegalAccessException)>(r2);<br/>/*141*/<br/>/*[not null]*/<br/>        $r8 = (java.lang.Throwable) $r7;<br/>/*141*/<br/>        throw $r8;<br/>/*141*/<br/>/*[not null]*/<br/><br/>        catch java.lang.IllegalAccessException from label1 to label2 with label2;<br/><br/>        localvar index=3 name=$i$a$1 type=I start=label1 end=label3;<br/>        localvar index=2 name=e$iv type=Ljava/lang/IllegalAccessException; start=label3 end=<end_of_method>;<br/>        localvar index=4 name=$i$f$reflectionCall type=I start=label1 end=<end_of_method>;<br/>        localvar index=0 name=$this type=Lkotlin/reflect/jvm/internal/KCallableImpl; start=label0 end=<end_of_method>;<br/>        localvar index=1 name=args type=[Ljava/lang/Object; start=label0 end=<end_of_method>;<br/>    }<br/></pre></div>"]
   body -> stmt0   stmt0 [label="r0 := @parameter0: kotlin.reflect.jvm.internal.KCallableImpl"];
   stmt1 [label="r1 := @parameter1: java.lang.Object[]"];
   stmt2 [label="staticinvoke <kotlin.jvm.internal.Intrinsics: void checkParameterIsNotNull(java.lang.Object,java.lang.String)>(r1, \"args\")"];
   stmt3 [label="$r3 = interfaceinvoke r0.<kotlin.reflect.jvm.internal.KCallableImpl: kotlin.reflect.jvm.internal.FunctionCaller getCaller()>()"];
   stmt4 [label="$r4 = virtualinvoke $r3.<kotlin.reflect.jvm.internal.FunctionCaller: java.lang.Object call(java.lang.Object[])>(r1)"];
   stmt5 [label="$r5 = (java.lang.Object) $r4"];
   stmt6 [label="return $r5"];
   stmt7 [label="$r6 := @caughtexception"];
   stmt8 [label="r2 = $r6"];
   stmt9 [label="$r7 = new kotlin.reflect.IllegalCallableAccessException"];
   stmt10 [label="specialinvoke $r7.<kotlin.reflect.IllegalCallableAccessException: void <init>(java.lang.IllegalAccessException)>(r2)"];
   stmt11 [label="$r8 = (java.lang.Throwable) $r7"];
   stmt12 [label="throw $r8"];
   stmt0 -> stmt1;
   stmt1 -> stmt2;
   stmt2 -> stmt3;
   stmt2 -> stmt7;
   stmt3 -> stmt4;
   stmt3 -> stmt7;
   stmt4 -> stmt5;
   stmt4 -> stmt7;
   stmt5 -> stmt6;
   stmt5 -> stmt7;
   stmt6 -> stmt7;
   stmt7 -> stmt8;
   stmt8 -> stmt9;
   stmt9 -> stmt10;
   stmt10 -> stmt11;
   stmt11 -> stmt12;
}

[DEBUG] Couldn't resolve local var $i$f$reflectionCall in kotlin.reflect.jvm.internal.KCallableImpl$DefaultImpls call<kotlin.reflect.jvm.internal.KCallableImpl$DefaultImpls: java.lang.Object call(kotlin.reflect.jvm.internal.KCallableImpl,java.lang.Object[])>
[ERROR] Couldn't compile app
java.util.UnknownFormatConversionException: Conversion = ' '
    at java.util.Formatter.checkText(Formatter.java:2579)
    at java.util.Formatter.parse(Formatter.java:2565)
    at java.util.Formatter.format(Formatter.java:2501)
    at java.util.Formatter.format(Formatter.java:2455)
    at java.lang.String.format(String.java:2940)
    at org.robovm.idea.RoboVmPlugin.log(RoboVmPlugin.java:487)
    at org.robovm.idea.RoboVmPlugin.logDebug(RoboVmPlugin.java:483)
    at org.robovm.idea.RoboVmPlugin$4.debug(RoboVmPlugin.java:514)
    at com.robovm.debug.compiler.DebugInfoPlugin.a(Unknown.java:719)
    at com.robovm.debug.compiler.DebugInfoPlugin.afterMethod(Unknown.java:499)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:802)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:297)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:301)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:384)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:444)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:773)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:53)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:59)
```

There are many similar [DEBUG] warnings before these until it eventually crashes.

Compiling in 'run' or 'release' mode this does not happen.

Possibly related to #1234

**Comment by badlogic** [comment]
Hm, that's not good. Looks like Kotlin's new local var info emission makes our debugger upset. I'll investigate. If you can provide a minimal repro sample i'd be much obliged.

**Comment by badlogic** [comment]
Ok, those errors are non-terminal. Kotlin 1.0 seems to have introduced a new null check.

`"%d".format(123)` turns into

```
33: invokestatic  #37                 // Method java/lang/String.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
36: dup
37: ldc           #39                 // String java.lang.String.format(this, *args)
39: invokestatic  #42                 // Method kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull:(Ljava/lang/Object;Ljava/lang/String;)V
```

Passing a method descriptor to Intrinsics.checkExpressionValueIsNotNull. That ldc actually introduces a local var table entry:

```
23      19     3 $i$f$format   I
```

We can't resolve that one, as it's a constant pool entry, so the debugger warns us about it. Some of those constants resolve to strings like `"%d"`. The crash was actually due to me passing that string verbatim to String.format when logging the event that that constant local var could not be resolved. 

Fixed, but you will still see the warnings that a local var could not be resolved. I brought this up with the Kotlin folks, i believe the local vars for those constants are superfluous.

**Comment by badlogic** [comment]
The fix will be available in the next RoboVM nightly build 1.13.1-SNAPSHOT in a few hours from now. Thanks for reporting.

**Comment by deadpixelsociety** [comment]
Well done, thanks.

**Comment by deadpixelsociety** [comment]
Tried to update my plugin to the latest nightly but the most recent build at http://download.robovm.org/files.html is from 2/16 for the IDEA plugin dist?

**Comment by badlogic** [comment]
Mea culpa, just started a new build, should be available in an hour or two.

**Comment by deadpixelsociety** [comment]
Thanks.
