### ISSUE TITLE
Enable bitcode error, libgdx 1.9.1, robovm 1.12.0

### ISSUE THREAD

**Issue by ldthai** [robovm/robovm#1241]
Hello
i got error:
`[ERROR] ld: -alias_list and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't create IPA
org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm5848511169796424876.tmp/thumbv7/IOSLauncher -arch armv7 -Wl,-filelist,/Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm5848511169796424876.tmp/thumbv7/objects0 -L /Users/ldthai/.robovm-sdks/robovm-1.14.0/lib/vm/ios/thumbv7 -ObjC -Xlinker -alias_list -Xlinker /Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm5848511169796424876.tmp/thumbv7/aliased_symbols -exported_symbols_list /Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm5848511169796424876.tmp/thumbv7/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/6a30f265691d027ff11448fc0739c848.extracted/META-INF/robovm/ios/libs -fPIC -miphoneos-version-min=7.0 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -lrobovm-bc -lrobovm-core -lgc -lpthread -ldl -lm -lz -framework Foundation -framework GoogleMobileAds -framework AdSupport -framework AudioToolbox -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreTelephony -framework EventKit -framework EventKitUI -framework MessageUI -framework StoreKit -framework SystemConfiguration -framework UIKit -framework OpenGLES -framework QuartzCore -framework OpenAL -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/dcb4bf31791a84f9cfb5a8098ab1eaf7.extracted/META-INF/robovm/ios/thumbv7/librobovm-rt-android.a -liconv -lsqlite3 -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/6a30f265691d027ff11448fc0739c848.extracted/META-INF/robovm/ios/libs/libGGLAdMob.a -lz -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/8567ea327a44de139de4e444c72b246b.extracted/META-INF/robovm/ios/libs/libGGLCore.a -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/b80d3d09e37d64a8bc3f42580b2976ad.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/b80d3d09e37d64a8bc3f42580b2976ad.extracted/META-INF/robovm/ios/libs/libObjectAL.a -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks' failed (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.exec(Executor.java:348)
    at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:398)
    at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:282)
    at org.robovm.compiler.target.ios.AppleDeviceTarget.doBuild(AppleDeviceTarget.java:528)
    at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:276)
    at org.robovm.compiler.Linker.link(Linker.java:439)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:411)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:741)
    at org.robovm.idea.compilation.RoboVmCompileTask$1.doCompile(RoboVmCompileTask.java:109)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:59)`

**Comment by intrigus** [comment]
Looks like this is a known bug https://github.com/robovm/robovm/issues/1226
