### ISSUE TITLE
ArrayIndexOutOfBoundsException on start of IntelliJ

### ISSUE THREAD

**Issue by intrigus** [robovm/robovm#1242]
I'm using IntelliJ 15.0.4, I've installed the plugin and this was the first launch.
I've done nothing special, I've only canceled the dialog that wanted to install the android sdk (This dialog was from RoboVM wasn't it?).
I hope that you can do something with this information :)

Stacktrace: 

```
1
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.robovm.compiler.target.ios.DeviceType.listDeviceTypes(DeviceType.java:124)
    at org.robovm.compiler.target.ios.DeviceType.listDeviceTypes(DeviceType.java:105)
    at org.robovm.idea.RoboVmPlugin.setupRunConfigurations(RoboVmPlugin.java:661)
    at org.robovm.idea.components.RoboVmSdkUpdateComponent$3$1.run(RoboVmSdkUpdateComponent.java:124)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
    at org.robovm.idea.components.RoboVmSdkUpdateComponent$3.run(RoboVmSdkUpdateComponent.java:98)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It looks similar to #1230 
But output of `~/.robovm-sdks/robovm-1.14.0/bin/ios-sim showdevicetypes` is

```
com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6s, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-2, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 9.2, (i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Air-2, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.iPad-Pro, 9.2, (x86_64 i386)
com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p, 9.1, (x86_64)
com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm, 2.1, (i386)
com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm, 2.1, (i386)
```

**Comment by davidgiga1993** [comment]
Has this ever been resolved?
I'm facing the same issue when launching the emulator.
