### ISSUE TITLE
LibGDX + Kotlin: Unjustified com.robovm.lm.UnlicensedException

### ISSUE THREAD

**Issue by ghost** [robovm/robovm#1246]
When using Kotlin with RoboVM and LibGDX, a typical launcher that translates 1:1 to its Java counterpart looks like this:

``` kotlin
class IOSLauncher : IOSApplication.Delegate() {
    override fun createApplication(): IOSApplication {
        val config = IOSApplicationConfiguration()
        return IOSApplication(Game(), config)
    }

    companion object {
        @JvmStatic fun main(argv: Array<String>) {
            val pool = NSAutoreleasePool()
            UIApplication.main<UIApplication, IOSLauncher>(argv, null, IOSLauncher::class.java)
            pool.close()
        }
    }
}
```

Now, if I want to use a more Kolin-esque approach by eliminating the companion object and use a free function like so:

``` kotlin
fun main(argv: Array<String>) {
    val pool = NSAutoreleasePool()
    UIApplication.main<UIApplication, IOSLauncher>(argv, null, IOSLauncher::class.java)
    pool.close()
}

class IOSLauncher : IOSApplication.Delegate() {
    override fun createApplication(): IOSApplication {
        val config = IOSApplicationConfiguration()
        return IOSApplication(Game(), config)
    }
}
```

I am getting a `com.robovm.lm.UnlicensedException`:

```
com.robovm.lm.UnlicensedException: Your RoboVM for indie game developers license can only be used for libGDX or PlayN games.
Please contact support@robovm.com if you believe this is an error.
    at com.robovm.lm.plugin.LicensePlugin.beforeClass(Unknown.java:43)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:705)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:297)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:254)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:337)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:397)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:732)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:53)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:59)
```

**Comment by badlogic** [comment]
The main class needs to inherit from IOSApplication.Delegate I'm afraid.

**Comment by ghost** [comment]
Alright, thanks Mario. Wanted to raise awareness for this. You can close if you are not going to fix this.
