### ISSUE TITLE
Soot fails to ignore unreachable exception handlers containing JSRs after JSR elimination

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#471]
When Soot eliminates JSRs in exception handlers it creates a copy of the handler. The old handler which still contains JSRs is kept though. The code which converts bytecode to Jimple traverses the CFG and all exception handlers, even those containing JSRs which aren't used anymore resulting in failure at runtime with the exception below. The relevant code is in `CFG.jimplify(cp_info constant_pool[],int this_class)`. It needs to ignore exception handlers which aren't reachable anymore.

This can be reproduced by linking against `lucene-core-3.2.0.jar` which can be downloaded from http://archive.apache.org/dist/lucene/java/3.2.0/.

```
Compiling org.apache.lucene.store.NativeFSLock (macosx x86 release)
java.lang.RuntimeException: Unrecognized bytecode instruction: 168
    at soot.coffi.CFG.generateJimple(CFG.java:4685)
    at soot.coffi.CFG.jimplify(CFG.java:1290)
    at soot.coffi.CFG.jimplify(CFG.java:978)
    at soot.coffi.CoffiMethodSource.getBody(CoffiMethodSource.java:98)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:87)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:321)
    at org.robovm.compiler.plugin.lambda.LambdaPlugin.transformMethod(LambdaPlugin.java:99)
    at org.robovm.compiler.plugin.lambda.LambdaPlugin.beforeClass(LambdaPlugin.java:85)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:545)
    at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:276)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:221)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:271)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:314)
    at org.robovm.compiler.AppCompiler.main(AppCompiler.java:552)
```

**Comment by boblebel** [comment]
Hi,
Just a note to let you know that this has now been fixed in Soot:

https://github.com/Sable/soot/issues/205
