### ISSUE TITLE
java.lang.ClassCastException: org.robovm.rt.bro.ptr.VoidPtr cannot be cast to org.robovm.apple.coretext.CTLine

### ISSUE THREAD

**Issue by samskivert** [robovm/robovm#577]
CTFrame.getLines is not being properly marshalled.

Apply the following patch to samples/HelloWorld:

```
diff --git i/HelloWorld/src/org/robovm/samples/helloworld/viewcontrollers/MyViewController.java w/HelloWorld/src/org/robovm/samples/helloworld/viewcontrollers/MyViewController.java
index 664f01d587..686264661d 100644
--- i/HelloWorld/src/org/robovm/samples/helloworld/viewcontrollers/MyViewController.java
+++ w/HelloWorld/src/org/robovm/samples/helloworld/viewcontrollers/MyViewController.java
@@ -19,8 +19,16 @@
 
 package org.robovm.samples.helloworld.viewcontrollers;
 
+import org.robovm.apple.corefoundation.CFRange;
+import org.robovm.apple.coregraphics.CGAffineTransform;
+import org.robovm.apple.coregraphics.CGPath;
 import org.robovm.apple.coregraphics.CGRect;
+import org.robovm.apple.coretext.CTFrame;
+import org.robovm.apple.coretext.CTFramesetter;
+import org.robovm.apple.coretext.CTLine;
+import org.robovm.apple.foundation.NSAttributedString;
 import org.robovm.apple.foundation.NSSet;
+import org.robovm.apple.uikit.NSAttributedStringAttributes;
 import org.robovm.apple.uikit.NSTextAlignment;
 import org.robovm.apple.uikit.UIBaselineAdjustment;
 import org.robovm.apple.uikit.UIColor;
@@ -96,6 +104,16 @@ public class MyViewController extends UIViewController {
     @Override
     public void viewDidLoad () {
         setupViews();
+
+      NSAttributedStringAttributes attrs = new NSAttributedStringAttributes();
+      NSAttributedString astr = new NSAttributedString("This is a test.", attrs);
+      CTFramesetter fs = CTFramesetter.create(astr);
+      CGPath path = CGPath.createWithRect(
+        new CGRect(0, 0, 200, Float.MAX_VALUE/2), CGAffineTransform.Identity());
+      CTFrame frame = fs.createFrame(new CFRange(0, 0), path, null);
+      for (CTLine line : frame.getLines()) {
+        System.err.println(line);
+      }
     }
 
     @Override
```

Then run it, and it will fail thusly:

```
[ERROR] java.lang.ClassCastException: org.robovm.rt.bro.ptr.VoidPtr cannot be cast to org.robovm.apple.coretext.CTLine
[ERROR] 
[ERROR] 	at org.robovm.samples.helloworld.viewcontrollers.MyViewController.viewDidLoad(MyViewController.java)
[ERROR] 	at org.robovm.apple.uikit.UIViewController.$cb$viewDidLoad(UIViewController.java)
[ERROR] 	at org.robovm.apple.uikit.UIWindow.$m$setRootViewController$(Native Method)
[ERROR] 	at org.robovm.apple.uikit.UIWindow.setRootViewController(UIWindow.java)
[ERROR] 	at org.robovm.samples.helloworld.HelloWorld.didFinishLaunching(HelloWorld.java)
[ERROR] 	at org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Unknown Source)
[ERROR] 	at org.robovm.apple.uikit.UIApplication.main(Native Method)
[ERROR] 	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
[ERROR] 	at org.robovm.samples.helloworld.HelloWorld.main(HelloWorld.java)
```

So it appears that the marshalling for the CTFrame.getLines call is not working properly. The method in question is declared as:

```java
    @Bridge(symbol="CTFrameGetLines", optional=true)
    public native @org.robovm.rt.bro.annotation.Marshaler(CFArray.AsListMarshaler.class) List<CTLine> getLines();
```

So maybe the magic of AsLIstMarshaler is not working?

**Comment by BlueRiverInteractive** [comment]
see #760
