### ISSUE TITLE
Dalvik test 018-stack-overflow fails on iOS devices

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#658]
Both 32-bit and 64-bit. On 32-bit the output looks like this:

```
/Users/niklas/Projects/robovm/tests/dalvik/018-stack-overflow: FAILED!

#################### info
# This is a miscellaneous test that was imported into the new-at-the-time
# runtime test framework. The test is intended to exercise basic features,
# and as such cannot be build on top of junit, since failure of such basic
# features might disrupt junit.
#
# TODO: Real description goes here.
#################### diffs
--- expected.txt    2013-02-24 09:30:02.000000000 +0100
+++ output.txt  2014-12-20 12:06:21.000000000 +0100
@@ -1,2 +1,2049 @@
-caught SOE
-SOE test done
+java.lang.NullPointerException
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
+   at Main.stackOverflowTestSub(Main.java:33)
...
+   at Main.stackOverflowTestSub(Main.java:33)
####################
```

On 64-bit:

```
/Users/niklas/Projects/robovm/tests/dalvik/018-stack-overflow: FAILED!

#################### info
# This is a miscellaneous test that was imported into the new-at-the-time
# runtime test framework. The test is intended to exercise basic features,
# and as such cannot be build on top of junit, since failure of such basic
# features might disrupt junit.
#
# TODO: Real description goes here.
#################### diffs
--- expected.txt    2013-02-24 09:30:02.000000000 +0100
+++ output.txt  2014-12-20 14:22:46.000000000 +0100
@@ -1,2 +0,0 @@
-caught SOE
-SOE test done
####################
```

**Comment by ntherning** [comment]
On 32-bit it's due to an incorrect stack address calculation for the main thread on iOS 8. Works fine for threads other than the main thread and on all threads on iOS 7.

On 64-bit the app crashes regardless of which thread SOE is triggered in.
