### ISSUE TITLE
Http requests crush in distribution by eclipse plugin

### ISSUE THREAD

**Issue by philwang2010** [robovm/robovm#715]
PathClassLoader: can't find '/private/var/mobile/Containers/Bundle/Application/1C6C0CD8-A7C8-4179-ABCE-78FB732FFF37/IOSLauncher.app/lib/boot/robovm-cacerts-full.jar'
java.lang.ExceptionInInitializerError
	at com.android.org.conscrypt.TrustedCertificateKeyStoreSpi.<init>(TrustedCertificateKeyStoreSpi.java)
	at java.lang.reflect.Constructor.internalNewInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java)
	at java.lang.Class.newInstance(Class.java)
	at java.security.Provider$Service.newInstance(Provider.java)
	at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java)
	at java.security.KeyStore.getInstance(KeyStore.java)
	at com.android.org.conscrypt.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java)
	at com.android.org.conscrypt.SSLParametersImpl.createDefaultTrustManager(SSLParametersImpl.java)
	at com.android.org.conscrypt.SSLParametersImpl.getDefaultTrustManager(SSLParametersImpl.java)
	at com.android.org.conscrypt.SSLParametersImpl.<init>(SSLParametersImpl.java)
	at com.android.org.conscrypt.SSLParametersImpl.getDefault(SSLParametersImpl.java)
	at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.<init>(OpenSSLSocketFactoryImpl.java)
	at java.lang.reflect.Constructor.internalNewInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java)
	at java.lang.Class.newInstance(Class.java)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java)
	at javax.net.ssl.HttpsURLConnection$NoPreloadHolder.<clinit>(HttpsURLConnection.java)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java)
	at com.android.okhttp.OkHttpClient.copyWithDefaults(OkHttpClient.java)
	at com.android.okhttp.OkHttpClient.open(OkHttpClient.java)
	at com.android.okhttp.OkHttpClient.open(OkHttpClient.java)
	at com.android.okhttp.HttpHandler.openConnection(HttpHandler.java)
	at java.net.URL.openConnection(URL.java)
	at com.badlogic.gdx.net.NetJavaImpl.sendHttpRequest(NetJavaImpl.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSNet.sendHttpRequest(IOSNet.java)
	at com.mygdx.game.MyGdxGame.create(MyGdxGame.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java)
	at org.robovm.apple.uikit.UIView.$cb$drawRect$(UIView.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at com.mygdx.game.IOSLauncher.main(IOSLauncher.java)
Caused by: java.lang.NullPointerException
	at com.android.org.conscrypt.TrustedCertificateStore.<clinit>(TrustedCertificateStore.java)

**Comment by philwang2010** [comment]
Run as iOS Device APP is OK
But Pack to IPA and Run Will Throw This Error

**Comment by philwang2010** [comment]
i changed the plugin version to 1.0.0.201412311508, resolved

**Comment by BlueRiverInteractive** [comment]
This is fixed with latest snapshot version.
