### ISSUE TITLE
@Marshaler CFType$NoRetainMarshalercan cannot be used to marshal AVAssetImageGenerator.$cb$copyCGImageAtTime$actualTime$error$ return type

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#814]
Weird. `MarshalerLookup` should try to search the `CFType` base class of `CGImage` for a suitable `toNative()` method since there is none in the `NoRetainMarshaler`. Might have to add `CFType.Marshaler` to the `AVAssetImageGenerator` class for this to work?

```
Compiling org.robovm.apple.avfoundation.AVAssetImageGenerator (linux x86_64 release)
java.lang.IllegalArgumentException: @Marshaler org.robovm.apple.corefoundation.CFType$NoRetainMarshaler specified for return type of @Callback method <org.robovm.apple.avfoundation.AVAssetImageGenerator: org.robovm.apple.coregraphics.CGImage $cb$copyCGImageAtTime$actualTime$error$(org.robovm.apple.avfoundation.AVAssetImageGenerator,org.robovm.objc.Selector,org.robovm.apple.coremedia.CMTime,org.robovm.apple.coremedia.CMTime,org.robovm.apple.foundation.NSError$NSErrorPtr)> can not be used to marshal org.robovm.apple.coregraphics.CGImage
        at org.robovm.compiler.MarshalerLookup.findMarshalerMethod(MarshalerLookup.java:156)
        at org.robovm.compiler.CallbackMethodCompiler.compileCallback(CallbackMethodCompiler.java:262)
        at org.robovm.compiler.CallbackMethodCompiler.doCompile(CallbackMethodCompiler.java:69)
        at org.robovm.compiler.AbstractMethodCompiler.compile(AbstractMethodCompiler.java:73)
        at org.robovm.compiler.ClassCompiler.callbackMethod(ClassCompiler.java:1277)
        at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:747)
        at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:285)
        at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:234)
        at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:291)
        at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:334)
        at org.robovm.compiler.AppCompiler.main(AppCompiler.java:588)
```

**Comment by ntherning** [comment]
When specifying an explicit marshaler on a return type or parameter we expect that marshaler to be able to handle the marshaling and we don't search upwards. The `CFType.NoRetainMarshaler` only defined a `toObject()` method for `@Bridge` methods. No `toNative()` for `@Callback` method. This hasn't been a problem before since we've only used it for `@Bridge` methods. Now with `AVAssetImageGenerator` we use it on a `@Method` which gets expanded into both a `@Bridge` and `@Callback` method. We should define an explicit `toNative()` in `CFType.NoRetainMarshaler` that delegates to `CFType.Marshaler.toNative()`. Also do the same for `NSObject.NoRetainMarshaler`.
