### ISSUE TITLE
Run libcore tests on 32- and 64-bit

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#828]

**Comment by badlogic** [comment]
x86 build output: https://gist.github.com/badlogic/6b17ed74dda084d43c7f
x86_65 build output: https://gist.github.com/badlogic/95e300760c7c899582fd

Both crash. The x86 version crashes due to the `FinalizerDaemon` timing out, which i guess is not good. The x86_64 version crashes in `[junit] testSetLongArray(libcore.io.MemoryTest)`.

The junit reports in `libcore/target/reports.xxx.xxx.xxx` are essentialy just saying that 1 test crashed. I guess that's the expected outcome.

I'll see if i can reproduce the crashes in standalone tests.

**Comment by badlogic** [comment]
The finalizer daemon timeout can't be reproduced when running the crashing test independently. I checked if the daemon has lowered priority, but it seems to run at default priority. I don't see any reason why the finalizer would take more than 10 seconds to finalize an object. I checked RandomAccessFile, the class that times out the finalizer. I don't see how its finalize method can block other than in native code that closes the file descriptor.

**Comment by badlogic** [comment]
The crash in MemoryTest on 64-bit is reproduceable when testing independently. The test assumes 32-bit wide pointers throughout. Fixing those to use long fixes the error.

After fixing this, the 64-bit tests fail the same way the 32-bit tests do. In the finalizer.

**Comment by badlogic** [comment]
Here's the stacktrace from the finalizer:

```
    [junit] [ERROR] android.System: java.io.RandomAccessFile.finalize() timed out after 10 seconds
    [junit] [ERROR] android.System: java.util.concurrent.TimeoutException: java.io.RandomAccessFile.finalize() timed out after 10 seconds
    [junit] 	at libcore.io.Posix.close(Native Method)
    [junit] 	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:75)
    [junit] 	at libcore.io.IoUtils.close(IoUtils.java:43)
    [junit] 	at java.io.RandomAccessFile.close(RandomAccessFile.java:166)
    [junit] 	at java.io.RandomAccessFile.finalize(RandomAccessFile.java:175)
    [junit] 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
    [junit] 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
    [junit] 	at java.lang.Thread.run(Thread.java:837)
```

**Comment by badlogic** [comment]
```bash
badlogic@Marios-MacBook-Pro:/tmp/robovm-libcore.auto.x86_64.20150306112759$ lldb ./test -- -rvm:mx256M -rvm:MainClass=RoboVMAllTests
(lldb) target create "./test"
Current executable set to './test' (x86_64).
(lldb) settings set -- target.run-args  "-rvm:mx256M" "-rvm:MainClass=RoboVMAllTests"
(lldb) b Java_java_lang_Runtime_nativeExit
Breakpoint 1: where = test`Java_java_lang_Runtime_nativeExit + 19 at java_lang_Runtime.c:20, address = 0x0000000100003263
(lldb) r
```
This way we end up in the finalizer watchdog daemon while the finalizer thread is still running.

**Comment by badlogic** [comment]
Giving up on this, some tests have NPEs as part of the test, and LLDB doesn't let us jump over EXC_BAD_ACCESS, see http://lists.cs.uiuc.edu/pipermail/lldb-dev/2013-July/002009.html

I used a modified `robovm-ant-junit-runner` to enable debug symbols and link in librobovm-debug which is supposed to fix the EXC_BAD_ACCESS issues, no dice.

```bash
if [ ! -x $TARGET/test ]; then
  export ROBOVM_DEV_ROOT=$BASE
  $ROBOVM_DEV_ROOT/bin/robovm \
    -tmp $TMP \
    -d $TARGET \
    -arch $ARCH \
    -os $OS \
    -o test \
    -verbose \
    -forcelinkclasses '##.#' \
    -debug \
    -use-debug-libs \
    -libs robovm-debug-dbg \
    -cp $CP
  result=$?
  if [ $result -ne 0 ]; then
    exit $result
  fi
  mkdir -p $TARGET/work
fi
```

**Comment by badlogic** [comment]
I'm closing this out in favor of #830.
