### ISSUE TITLE
Crash playing an aac encoded (.m4a) audio file.

### ISSUE THREAD

**Issue by AgrarPirat** [robovm/robovm#836]
Hello,

the following crash happens when trying to play an aac encoded (.m4a) sound effect. Playing aac encoded background music is working fine. Oddly enough, the xCode device log does not list the crah. It's working fine on android. Project configuration is:
gdxVersion = '1.5.5-SNAPSHOT'
roboVMVersion = '1.0.0-SNAPSHOT'
Do you have any ideas what might cause this issue or how to workaround it?

> 2015-03-09 05:36:29.165 IOSLauncher[16614:1349028] -[OALSimpleAudio playBuffer:volume:pitch:pan:loop]: unrecognized selector sent to instance 0x14d49cc0
2015-03-09 05:36:29.167 IOSLauncher[16614:1349028] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OALSimpleAudio playBuffer:volume:pitch:pan:loop]: unrecognized selector sent to instance 0x14d49cc0'
*** First throw call stack:
(0x2c79a5f7 0x3a2e8c77 0x2c79fabd 0x2c79d999 0x2c6ceb88 0x3c9bff 0x3c8b7f 0x3c091b 0x3c0887 0x4bc5f3 0x44a9f1 0x44c0a9 0x3ad691 0x3bde7f 0x3bc40d 0x3bc923 0xac2fbb 0xac305d 0xacf405 0x2d5ff7b9 0x2d6008db 0x2f6b8aeb 0x2f6b8953 0x33f6f82f 0x2d6c41ed 0x2c7503a5 0x2c7607f3 0x2c76078f 0x2c75edb1 0x2c6abb31 0x2c6ab943 0x33a62051 0x2fca16f1 0x9481f5 0x947745 0x947783 0x4aeb5f 0xb4e19b 0xb46ebf 0xb48b3b 0xb48b95 0xb42e89 0xb3b4ed 0x2b1080)
libc++abi.dylib: terminating with uncaught exception of type NSException
AppLauncher failed with an exception:
java.lang.RuntimeException: The app crashed: Terminated due to signal 6. Check the device logs in Xcode (Window->Devices) for more info.
	at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:829)
	at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:734)
	at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1052)
	at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)

**Comment by badlogic** [comment]
There was a bug in libGDX which has already been fixed. Please update libGDX to the latest nightlies.

**Comment by AgrarPirat** [comment]
Thank you!
