### ISSUE TITLE
Implement proper shutdown sequence

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#85]
System.exit(0) runs all shutdown hooks so we probably want to call it after all non-daemon threads have finished.

**Comment by xranby** [comment]
I have an use-case that is occasionally crashing inside the NVIDIA OpenGL driver during JVM teardown and i have a hunch that it is caused by incorrect thread termination order and possibly that we do not run the java System registered shutdown hooks at the right time.

here is my test example that can quite frequently reproduce the issue. each com.jogamp.newt.opengl.GLWindow test run only takes half a second.

#get jogamp and robovm
wget http://download.robovm.org/nightlies/robovm-1.6.1-SNAPSHOT-20150820_014200-647.tar.gz
wget http://jogamp.org/deployment/archive/master/gluegen_885-joal_611-jogl_1424-jocl_1073/fat/jogamp-fat.jar

#unpack
tar zxvf robovm-1.6.1-SNAPSHOT-20150820_014200-647.tar.gz

#compile using robovm
./robovm-1.6.1-SNAPSHOT/bin/robovm -verbose -dynamic-jni -forcelinkclasses jogamp.**:com.jogamp.** -cp jogamp-fat.jar com.jogamp.newt.opengl.GLWindow

#run
cd com.jogamp.newt.opengl.GLWindow 
#robovm currently fail to find natives inside jars, unpack them
unzip lib/jogamp-fat.jar natives/*/*
time ./com.jogamp.newt.opengl.GLWindow

**Comment by xranby** [comment]
a typical log of the above mentioned crash looks like this, as you can see there is no robovm frames on the stack when it happens thus this is caused by incorrect order of freeing memory during application teardown, likely robovm has freed memory used by the GPU driver, something that the registered shutdown hooks should guarantee not to happen.

output and gdb backtrace:
GL3 retrieved, impl. class jogamp.opengl.gl4.GL4bcImpl

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffda18f700 (LWP 24084)]
0x00007fffe63a9bf6 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
(gdb) bt
#0  0x00007fffe63a9bf6 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#1  0x00007fffe642f03a in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#2  0x00007fffe63e5aab in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#3  0x00007fffe63e705f in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#4  0x00007fffe63aaace in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#5  0x00007fffe794f39b in ?? () from /usr/lib/nvidia-331-updates/libGL.so.1
#6  0x00007ffff7bc3f82 in __nptl_deallocate_tsd () at pthread_create.c:158
#7  0x00007ffff7bc4195 in start_thread (arg=0x7fffda18f700) at pthread_create.c:325
#8  0x00007ffff6c4c47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) info threads
  Id   Target Id         Frame 
* 14   Thread 0x7fffda18f700 (LWP 24084) "com.jogamp.newt" 0x00007fffe63a9bf6 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
  13   Thread 0x7fffe409f700 (LWP 24083) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7fffe4120700 (LWP 24082) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7fffe41a1700 (LWP 24081) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7ffff4083700 (LWP 24080) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7ffff4104700 (LWP 24079) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7ffff4185700 (LWP 24078) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7ffff51b4700 (LWP 24077) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7ffff5235700 (LWP 24076) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7ffff52b6700 (LWP 24075) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7ffff7e9f700 (LWP 24074) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7ffff7f20700 (LWP 24073) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7ffff7fa1700 (LWP 24072) "com.jogamp.newt" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  1    Thread 0x7ffff7fc3780 (LWP 24071) "com.jogamp.newt" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
(gdb) frame 1
#1  0x00007fffe642f03a in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
(gdb) bt
#0  0x00007fffe63a9bf6 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#1  0x00007fffe642f03a in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#2  0x00007fffe63e5aab in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#3  0x00007fffe63e705f in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#4  0x00007fffe63aaace in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#5  0x00007fffe794f39b in ?? () from /usr/lib/nvidia-331-updates/libGL.so.1
#6  0x00007ffff7bc3f82 in __nptl_deallocate_tsd () at pthread_create.c:158
#7  0x00007ffff7bc4195 in start_thread (arg=0x7fffda18f700) at pthread_create.c:325
#8  0x00007ffff6c4c47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

**Comment by badlogic** [comment]
GPU drivers are responsible for safe guarding their resources from process
crashes and properly managing them in such a worst case scenario. Just lioe
the OS manages heap memory in case of program failure.

I totally agree that we should eventually implement the proper shutdown
sequence hooks. But my experience with GPUs, window toolkits and drivers
over the years tells me you must be doing something not so nice for the
driver to totally give up.

It's unlikely that will focus on this issue in the short term, so it may be
a good idea to review Newt and see if there's something going on that's bad.

**Comment by xranby** [comment]
i tried to reproduce the issue using a new nvidia driver such as 355.00.05 on my fedora 22 machine.. but it runs stable.. cant reproduce it using a new driver
