### ISSUE TITLE
Better error message when app on device is killed or crashes

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#902]
Now we just treat this a kill as any other crash:

```
4/15/15 3:51:06 PM: [ERROR] AppLauncher failed with an exception:
4/15/15 3:51:06 PM: [ERROR] java.lang.RuntimeException: The app crashed: Terminated due to signal 9. Check the device logs in Xcode (Window->Devices) for more info.
4/15/15 3:51:06 PM: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:829)
4/15/15 3:51:06 PM: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:734)
4/15/15 3:51:06 PM: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1052)
4/15/15 3:51:06 PM: [ERROR] 	at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)
```

But the reason could be that the user launched the app again. Then iOS will kill the app and then launch the new version. Another reason for a signal 9 could be that the app took to long to startup and iOS kills it for that reason. We could say something like: 

> The app was killed. If you killed it manually or relaunched it this is normal. Otherwise it could be that the app took too long to startup. Check the device logs in Xcode (Window->Devices) for more info. 

instead of mentioning the signal number. And don't show the stacktrace, ever. It doesn't add any value for any type of signal really. Also, use `WARN` for signal 9?

For other signal numbers we could translate the signal number into the signal name (`SIGSEGV`, `SIGBUS`, etc). And again, no stacktrace.

**Comment by BlueRiverInteractive** [comment]
This issue is very similar: https://github.com/robovm/robovm/issues/685
