### ISSUE TITLE
Error on displaying non-line-based error messages when license is activated

### ISSUE THREAD

**Issue by abram** [robovm/robovm#903]
I ran into an issue this morning where Gradle didn't have enough heap space, and my build would fail with the message:

```
BUILD FAILED
...
Java heap space
```

That's without a license activated. However, with a license activated I get this message instead:

```
BUILD FAILED
...
Line number must not be < 1
```

It appears that the original error message has been swallowed up, and instead RoboVM is attempting to parse the error message for a line number and failing. I can work around this for the moment by temporarily disabling my license any time I run into a `Line number must not be < 1` message in order to see the real error, but it would be nicer if this was fixed :). Thanks!

**Comment by ntherning** [comment]
Could you please show us the stacktrace of that "Line number must not be < 1" error please? Run Gradle using `--stacktrace`.

**Comment by abram** [comment]
Here you go:
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launchIPhoneSimulator'.
> Failed to launch IOS Simulator

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':launchIPhoneSimulator'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:48)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.api.GradleException: Failed to launch IOS Simulator
	at org.robovm.gradle.tasks.AbstractIOSSimulatorTask.launch(AbstractIOSSimulatorTask.java:81)
	at org.robovm.gradle.tasks.IPhoneSimulatorTask.invoke(IPhoneSimulatorTask.java:31)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 56 more
Caused by: java.lang.IllegalArgumentException: Line number must not be < 1
	at com.robovm.debug.compiler.m.a(Unknown.java:48)
	at com.robovm.debug.compiler.DebugInfoPlugin.afterMethod(Unknown.java:305)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:766)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:285)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:242)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:331)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:375)
	at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:96)
	at org.robovm.gradle.tasks.AbstractIOSSimulatorTask.launch(AbstractIOSSimulatorTask.java:37)
	... 65 more


```

**Comment by ntherning** [comment]
Could you please provide us with a minimal test app that reproduces this problem? The bytecode of some class being compiled causes this exception in the compiler. We need to get our hands on the bytecode and preferably the original source code.

**Comment by cvermilion** [comment]
I think experienced a similar issue; the build would reliably fail at a certain step in compiling the Clojure core into the RoboVM app. What ultimately solved it was deactivating my license key -- somehow the debug plugin was the problem:

> 14:29:53.217 [INFO] [org.gradle.api.Task] Compiling RoboVM app, this could take a while, especially the first time round
> 14:29:54.544 [DEBUG] [org.gradle.api.Task] Compiling classes using 4 threads
> 14:29:54.805 [DEBUG] [org.gradle.api.Task] Compiling clojure.core$build_positional_factory$iter__6232__6236$fn__6237$fn__6238 (ios x86 release)
 >14:29:55.862 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':launchIPhoneSimulator'
> 14:29:55.862 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :launchIPhoneSimulator FAILED

**Comment by abram** [comment]
I'm having trouble creating this with RoboVM 1.2 and a basic gradle-based setup on the command line. It must have been related to my IntelliJ setup (which I'm no longer using). Feel free to close if you can't reproduce, I'll re-open if and when I'm able to to create an isolated way to reproduce.

**Comment by abram** [comment]
After some more debugging I'm now able to reproduce it consistently. I created a sample repository here that demonstrates the problem: https://github.com/abram/robovm-line-number-bug-demo

**Comment by chgraham** [comment]
Using IntellJ IDEA Community Edition, unless I deactivate my license, the compilation of Clojure for RoboVM fails with the "Line number must not be < 1" message, no matter how generous I am with "-Xmx" in the idea.vmoptions file.

**Comment by ntherning** [comment]
I'm debugging another clojure project which is also fails with the "Line number must not be < 1" error. It looks like the clojure compiler generates a line number table containing line 0 for the `clojure.core$build_positional_factory$iter__6232__6236$fn__6237$fn__6238.invoke()` method. This makes our debug info plugin throw an exception as it expects all line numbers to be 1 or more. We'll have to workaround this by filtering out bad line numbers like 0.

**Comment by ntherning** [comment]
@abram nothing gets swallowed. When the license is activated the compilation fails earlier due to the debug info plugin not being able to cope with the line number table generated by the clojure compiler. If you disable the license this plugin is also disabled and the compilation can proceed. If the heap is too small it will then eventually fail with on OOM.

I have run your repository with a patch debug info plugin which works around the bad line number tables generated by the clojure compiler and it now happily compiles and runs in the simulator. I have started a new snapshot build which should be available in an hour or so. Please try it out and report back whether the "Line number must not be < 1" issue is gone when you have your license activated. See http://docs.robovm.com/advanced-topics/nightlies.html#gradle for info on how to use the snapshots.

**Comment by abram** [comment]
I just tried it and I can confirm this fixes the issue. Thanks so much!
