### ISSUE TITLE
Error in Idea plugin when importing HelloWorld sample

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#940]
Stacktrace:

	null
	java.lang.NullPointerException
		at org.robovm.idea.RoboVmPlugin.isRoboVmModule(RoboVmPlugin.java:338)
		at org.robovm.idea.interfacebuilder.IBIntegratorModuleComponent.moduleAdded(IBIntegratorModuleComponent.java:46)
		at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:232)
		at com.intellij.openapi.module.impl.ModuleManagerImpl$6.run(ModuleManagerImpl.java:998)
		at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:363)
		at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModel(ModuleManagerImpl.java:954)
		at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1300(ModuleManagerImpl.java:73)
		at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commitWithRunnable(ModuleManagerImpl.java:850)
		at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:599)
		at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:48)
		at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:37)
		at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commit(ModuleManagerImpl.java:846)
		at com.intellij.openapi.module.impl.ModuleManagerImpl.newModule(ModuleManagerImpl.java:475)
		at com.intellij.openapi.externalSystem.service.project.manage.ModuleDataService$2.importModule(ModuleDataService.java:110)
		at com.intellij.openapi.externalSystem.service.project.manage.ModuleDataService$2.run(ModuleDataService.java:104)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
		at com.intellij.openapi.externalSystem.service.project.manage.ModuleDataService.createModules(ModuleDataService.java:99)
		at com.intellij.openapi.externalSystem.service.project.manage.ModuleDataService.access$100(ModuleDataService.java:41)
		at com.intellij.openapi.externalSystem.service.project.manage.ModuleDataService$1.execute(ModuleDataService.java:83)
		at com.intellij.openapi.externalSystem.util.DisposeAwareProjectChange.run(DisposeAwareProjectChange.java:36)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7$1.run(ExternalSystemApiUtil.java:462)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7.run(ExternalSystemApiUtil.java:459)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeOnEdt(ExternalSystemApiUtil.java:472)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeProjectChangeAction(ExternalSystemApiUtil.java:457)
		at com.intellij.openapi.externalSystem.service.project.manage.ModuleDataService.importData(ModuleDataService.java:78)
		at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:113)
		at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:95)
		at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:121)
		at com.intellij.openapi.externalSystem.service.project.wizard.AbstractExternalProjectImportBuilder$1$1$1.run(AbstractExternalProjectImportBuilder.java:144)
		at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:328)
		at com.intellij.openapi.externalSystem.service.project.wizard.AbstractExternalProjectImportBuilder$1$1.execute(AbstractExternalProjectImportBuilder.java:141)
		at com.intellij.openapi.externalSystem.util.DisposeAwareProjectChange.run(DisposeAwareProjectChange.java:36)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7$1.run(ExternalSystemApiUtil.java:462)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7.run(ExternalSystemApiUtil.java:459)
		at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2379)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeOnEdt(ExternalSystemApiUtil.java:479)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeProjectChangeAction(ExternalSystemApiUtil.java:457)
		at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeProjectChangeAction(ExternalSystemApiUtil.java:453)
		at com.intellij.openapi.externalSystem.service.project.wizard.AbstractExternalProjectImportBuilder$1.run(AbstractExternalProjectImportBuilder.java:138)
		at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:339)
		at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:59)
		at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:174)
		at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:146)
		at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:171)
		at com.intellij.ide.startup.impl.StartupManagerImpl.access$1000(StartupManagerImpl.java:59)
		at com.intellij.ide.startup.impl.StartupManagerImpl$4.run(StartupManagerImpl.java:205)
		at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:269)
		at com.intellij.openapi.project.DumbServiceImpl.access$800(DumbServiceImpl.java:52)
		at com.intellij.openapi.project.DumbServiceImpl$9.run(DumbServiceImpl.java:439)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Screenshot: [screen shot 2015-04-24 at 9 43 24 am](https://cloud.githubusercontent.com/assets/1442206/7313844/9629895c-ea66-11e4-9186-ac34b2bfd4ac.png)

**Comment by magicgoose** [comment]
The same error when trying to import ContactR sample. (and probably any other samples)

**Comment by badlogic** [comment]
Thanks for reporting. We already fixed this error. You can install a
snapshot build of the IDEA plugin following the instructions at
http://docs.robovm.com/getting-started/intellij.html

We do a release soonish!

**Comment by magicgoose** [comment]
Thanks, will try installing it. :+1:
