### ISSUE TITLE
XCode plugins like Unity may interfere with RoboVM build

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#959]
See https://groups.google.com/forum/m/?hl=en&fromgroups#!topic/robovm/j8fx8FaPQ80

**Comment by badlogic** [comment]
```
[ERROR] Couldn't compile app 
java.io.IOException: Cannot run program "2015-07-28 19:02:30.817 xcodebuild[1393:137286] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs 
2015-07-28 19:02:30.820 xcodebuild[1393:137286] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs 
2015-07-28 19:02:30.822 xcodebuild[1393:137286] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++": error=2, No such file or directory 
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) 
at java.lang.Runtime.exec(Runtime.java:620) 
at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58) 
at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:246) 
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:302) 
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149) 
at org.robovm.compiler.util.Executor.exec(Executor.java:344) 
at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:371) 
at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:250) 
at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:348) 
at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:244) 
at org.robovm.compiler.Linker.link(Linker.java:424) 
at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:464) 
at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60) 
at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66) 
Caused by: java.io.IOException: error=2, No such file or directory 
at java.lang.UNIXProcess.forkAndExec(Native Method) 
at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) 
at java.lang.ProcessImpl.start(ProcessImpl.java:134) 
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) 
... 14 more
```

**Comment by badlogic** [comment]
Related discussion by the Alcatraz folks: https://github.com/supermarin/Alcatraz/issues/73

It appears there's no alternative to updating the Info.plist of the plugin, which should be the plugin maintainers responsibility.

**Comment by badlogic** [comment]
Manual workaround, may break the plugin if it's not compatible with the Xcode version for which the UUID is added manually to the `Info.plist`: http://stackoverflow.com/a/22363319

**Comment by colemarkham** [comment]
I deleted the offending plugins, but the RoboVM build is still showing the error message when I try to run for iOS.

**Comment by ollyde** [comment]
I still have this issue but cannot uninstall Unity. Any solution?
I don't quite understand the UUID bit, do you mean the UUID of libgdxs project signature or the UUID of the device or..?

**Comment by badlogic** [comment]
Can you try updating Unity? Otherwise the only solution is to temporarily
move the Unity Xcode plugin out of that folder. We are not in control of
3rd party plugins.

**Comment by ollyde** [comment]
I updated unity then I added the UUID that was logged from the error in LibGDX to the plist file. (~/library/Application Support/Developer/Shared/Xcode/Plug-ins/Content/info.plist)
Thing is, UUID would not register until I actually restarted the mac (I tried various things like restarting xcode etc)
It's working great now on 1.8 thanks.

**Comment by ntherning** [comment]
I believe this has been fixed now. We now only capture stdout when running xcrun to find the paths to Xcode command line tools. Will close this as fixed.
