### ISSUE TITLE
forEach method fails to compile

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#964]
`Iterable.forEach` method (added in Java 8) breaks the compilation. But there's no problem when using for (iteration) loop.

Stacktrace from build log:

	org.robovm.compiler.CompilerException: org.robovm.compiler.plugin.lambda.java.lang.invoke.LambdaConversionException: Functional interface java.util.function.Consumer is not an interface
		at org.robovm.compiler.plugin.lambda.LambdaPlugin.transformMethod(LambdaPlugin.java:172)
		at org.robovm.compiler.plugin.lambda.LambdaPlugin.beforeClass(LambdaPlugin.java:85)
		at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:672)
		at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:285)
		at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:242)
		at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:331)
		at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:375)
		at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
		at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
	Caused by: org.robovm.compiler.plugin.lambda.java.lang.invoke.LambdaConversionException: Functional interface java.util.function.Consumer is not an interface
		at org.robovm.compiler.plugin.lambda.java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:147)
		at org.robovm.compiler.plugin.lambda.java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:157)
		at org.robovm.compiler.plugin.lambda.java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:300)
		at org.robovm.compiler.plugin.lambda.LambdaPlugin.transformMethod(LambdaPlugin.java:121)
		... 8 more

**Comment by badlogic** [comment]
RoboVM currently only supports the Java 8 language features (lambdas).
Support for Java 8 APIs like streams etc. Is in the works.

**Comment by ntherning** [comment]
Yes `Iterable.forEach` is not supported by our runtime. We're looking into ways to support the Java 8 APIs.
