### ISSUE TITLE
arm64 release crashes with NPE

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#966]
The app crashes ONLY in arm64 release mode (iPhone 6 8.3). Tested within Eclipse

To replicate create a new robovm project in Eclipse (without storyboard). Remove the view controller class, we only want the application delegate. Create a new class `Util`.

The contents of the two classes should be as follows:

```Java
public class Sample extends UIApplicationDelegateAdapter {
    @Override
    public boolean didFinishLaunching(UIApplication application, UIApplicationLaunchOptions launchOptions) {
        Util.formatTime(1000, 4);
        return true;
    }

    public static void main(String[] args) {
        NSAutoreleasePool pool = new NSAutoreleasePool();
        UIApplication.main(args, null, Sample.class);
        pool.close();
    }
}
```

```Java
public class Util {
    public static String formatTime(long milliseconds, int digits) {
        int ms = (int) (milliseconds % 1000);
        int seconds = (int) (milliseconds / 1000) % 60;
        int minutes = (int) ((milliseconds / (1000 * 60)) % 60);
        int hours = (int) ((milliseconds / (1000 * 60 * 60)) % 24);

        switch (digits) {
        case 1:
            return String.format("%02d", seconds);
        case 2:
            return String.format("%02d:%02d", minutes, seconds);
        case 3:
            return String.format("%02d:%02d:%02d", hours, minutes, seconds);
        default:
            return String.format("%02d:%02d:%02d.%03d", hours, minutes, seconds, ms);
        }
    }
}
```

It will crash with a NPE only in arm64:
```
java.lang.NullPointerException
	at org.robovm.test.Util.formatTime(Util.java:6)
	at org.robovm.test.Sample.didFinishLaunching(Sample.java:19)
	at org.robovm.test.Sample.$cb$application$didFinishLaunchingWithOptions$(Sample.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:368)
	at org.robovm.test.Sample.main(Sample.java:26)

```

**Comment by badlogic** [comment]
Assembler:

```gas
.globl	"_[J]Util.formatTime(JI)Ljava/lang/String;"
	.align	2
"_[J]Util.formatTime(JI)Ljava/lang/String;": ; @"[J]Util.formatTime(JI)Ljava/lang/String;"
Lfunc_begin3:
	.loc	1 3 0                   ; Util.java:3:0
	.cfi_startproc
; BB#0:                                 ; %label0
	stp	x24, x23, [sp, #-64]!
	stp	x22, x21, [sp, #16]
	stp	x20, x19, [sp, #32]
	stp	x29, x30, [sp, #48]
	add	x29, sp, #48            ; =48
Ltmp13:
	.cfi_def_cfa w29, 16
Ltmp14:
	.cfi_offset w30, -8
Ltmp15:
	.cfi_offset w29, -16
Ltmp16:
	.cfi_offset w19, -24
Ltmp17:
	.cfi_offset w20, -32
Ltmp18:
	.cfi_offset w21, -40
Ltmp19:
	.cfi_offset w22, -48
Ltmp20:
	.cfi_offset w23, -56
Ltmp21:
	.cfi_offset w24, -64
	mov	 x19, x0
	; InlineAsm Start
	sub	x9, sp, #16, lsl #12    ; =65536
	; InlineAsm End
	movz	x8, #0x20c4, lsl #48
	movk	x8, #0x9ba5, lsl #32
	movk	x8, #0xe353, lsl #16
	movk	x8, #0xf7cf
	movn	x9, #0x7777, lsl #16
	movk	x9, #0x8889
	movz	x10, #0x45e7, lsl #48
	movk	x10, #0xb272, lsl #32
	movk	x10, #0xf608, lsl #16
	movk	x10, #0x770f
	movz	x11, #0x4a90, lsl #48
	movk	x11, #0xbe58, lsl #32
	movk	x11, #0x7de6, lsl #16
	movk	x11, #0xe565
	orr	x12, xzr, #0xaaaaaaaaaaaaaaaa
	movk	x12, #0xaaab
	movk	x12, #0x2aaa, lsl #48
	.loc	1 6 0 prologue_end      ; Util.java:6:0
Ltmp22:
	smulh	x11, x1, x11
	asr	x13, x11, #20
	add	x11, x13, x11, lsr #63
	smulh	x12, x11, x12
	lsr	x13, x12, #63
	lsr	x12, x12, #2
	add	 w12, w12, w13
	orr	w13, wzr, #0x18
	msub	w22, w12, w13, w11
	orr	x11, xzr, #0x8888888888888888
	movk	x11, #0x8889
	.loc	1 4 0                   ; Util.java:4:0
	smulh	x8, x1, x8
	.loc	1 5 0                   ; Util.java:5:0
	smulh	x10, x1, x10
	.loc	1 4 0                   ; Util.java:4:0
	asr	x12, x8, #7
	add	x8, x12, x8, lsr #63
	.loc	1 5 0                   ; Util.java:5:0
	asr	x12, x10, #14
	add	x10, x12, x10, lsr #63
	.loc	1 4 0                   ; Util.java:4:0
	sxtw	x12, w8
	.loc	1 5 0                   ; Util.java:5:0
	smulh	x11, x10, x11
	.loc	1 4 0                   ; Util.java:4:0
	mul	 x9, x12, x9
	.loc	1 5 0                   ; Util.java:5:0
	add	 x11, x11, x10
	lsr	x12, x11, #63
	lsr	x11, x11, #5
	add	 w11, w11, w12
	orr	w12, wzr, #0x3c
	.loc	1 4 0                   ; Util.java:4:0
	lsr	x9, x9, #32
	add	 w9, w9, w8
	.loc	1 5 0                   ; Util.java:5:0
	msub	w21, w11, w12, w10
	.loc	1 4 0                   ; Util.java:4:0
	asr	w10, w9, #5
	add	w10, w10, w9, lsr #31
	; InlineAsm Start
	ldr	 x9, [x9]
	; InlineAsm End
	msub	w20, w10, w12, w8
	.loc	1 8 0                   ; Util.java:8:0
	cmp	 w2, #3                 ; =3
	b.eq	LBB3_3
; BB#1:                                 ; %label0
	cmp	 w2, #2                 ; =2
	b.ne	LBB3_4
; BB#2:                                 ; %label2
	orr	w1, wzr, #0x2
	.loc	1 12 0                  ; Util.java:12:0
	mov	 x0, x19
	bl	"_[j][Ljava/lang/Object;[anewarray]"
	mov	 x22, x0
	mov	 x0, x19
	mov	 w1, w21
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	mov	 w2, wzr
	mov	 x0, x19
	mov	 x1, x22
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	mov	 w1, w20
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	orr	w2, wzr, #0x1
	mov	 x0, x19
	mov	 x1, x22
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	bl	"_[j]str__2502d_3A_2502d_00[ldcstring]"
	mov	 x1, x0
	mov	 x0, x19
	mov	 x2, x22
	b	LBB3_7
LBB3_3:                                 ; %label3
	orr	w1, wzr, #0x3
	.loc	1 14 0                  ; Util.java:14:0
	mov	 x0, x19
	bl	"_[j][Ljava/lang/Object;[anewarray]"
	mov	 x23, x0
	mov	 x0, x19
	mov	 w1, w22
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	mov	 w2, wzr
	mov	 x0, x19
	mov	 x1, x23
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	mov	 w1, w21
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	orr	w2, wzr, #0x1
	mov	 x0, x19
	mov	 x1, x23
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	mov	 w1, w20
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	orr	w2, wzr, #0x2
	mov	 x0, x19
	mov	 x1, x23
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	bl	"_[j]str__2502d_3A_2502d_3A_2502d_00[ldcstring]"
	mov	 x1, x0
	mov	 x0, x19
	mov	 x2, x23
	b	LBB3_7
LBB3_4:                                 ; %label0
	cmp	 w2, #1                 ; =1
	b.ne	LBB3_6
; BB#5:                                 ; %label1
	orr	w1, wzr, #0x1
	.loc	1 10 0                  ; Util.java:10:0
	mov	 x0, x19
	bl	"_[j][Ljava/lang/Object;[anewarray]"
	mov	 x21, x0
	mov	 x0, x19
	mov	 w1, w20
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	mov	 w2, wzr
	mov	 x0, x19
	mov	 x1, x21
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	bl	"_[j]str__2502d_00[ldcstring]"
	mov	 x1, x0
	mov	 x0, x19
	mov	 x2, x21
	b	LBB3_7
LBB3_6:                                 ; %label4
	movz	x8, #0x20c4, lsl #48
	movk	x8, #0x9ba5, lsl #32
	movk	x8, #0xe353, lsl #16
	movk	x8, #0xf7cf
	.loc	1 3 0                   ; Util.java:3:0
	smulh	x8, x1, x8
	lsr	x9, x8, #63
	lsr	x8, x8, #7
	add	 w8, w8, w9
	movz	w9, #0x3e8
	msub	w23, w8, w9, w1
	orr	w1, wzr, #0x4
	.loc	1 16 0                  ; Util.java:16:0
	mov	 x0, x19
	bl	"_[j][Ljava/lang/Object;[anewarray]"
	mov	 x24, x0
	mov	 x0, x19
	mov	 w1, w22
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	mov	 w2, wzr
	mov	 x0, x19
	mov	 x1, x24
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	mov	 w1, w21
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	orr	w2, wzr, #0x1
	mov	 x0, x19
	mov	 x1, x24
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	mov	 w1, w20
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	orr	w2, wzr, #0x2
	mov	 x0, x19
	mov	 x1, x24
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	mov	 w1, w23
	bl	"_[j]java.lang.Integer.valueOf(I)Ljava/lang/Integer;[clinit]"
	mov	 x3, x0
	orr	w2, wzr, #0x3
	mov	 x0, x19
	mov	 x1, x24
	bl	__bcSetObjectArrayElement
	mov	 x0, x19
	bl	"_[j]str__2502d_3A_2502d_3A_2502d_2E_2503d_00[ldcstring]"
	mov	 x1, x0
	mov	 x0, x19
	mov	 x2, x24
LBB3_7:                                 ; %label1
	.loc	1 10 0                  ; Util.java:10:0
	bl	"_[j]java.lang.String.format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;[clinit]"
	ldp	x29, x30, [sp, #48]
	ldp	x20, x19, [sp, #32]
	ldp	x22, x21, [sp, #16]
	ldp	x24, x23, [sp], #64
	ret
Ltmp23:
Lfunc_end3:
"L_[J]Util.formatTime(JI)Ljava/lang/String;_end":

	.cfi_endproc
```

**Comment by badlogic** [comment]
Reduced method to:

```java
public class Util {
    public static String formatTime(long milliseconds, int digits) {
        int ms = (int) (milliseconds % 1000);
        int seconds = (int) (milliseconds / 1000) % 60;
        int minutes = (int) ((milliseconds / (1000 * 60)) % 60);
        int hours = (int) ((milliseconds / (1000 * 60 * 60)) % 24);
        return "" + ms + " " + seconds + " " + minutes + " " + hours;
}
```

Assembler, 64-bit ARM, release:

```gas
	.globl	"_[J]Util.formatTime(JI)Ljava/lang/String;"
	.align	2
"_[J]Util.formatTime(JI)Ljava/lang/String;": ; @"[J]Util.formatTime(JI)Ljava/lang/String;"
Lfunc_begin3:
	.loc	1 3 0                   ; Util.java:3:0
	.cfi_startproc
; BB#0:                                 ; %label0
	stp	x22, x21, [sp, #-48]!
	stp	x20, x19, [sp, #16]
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32            ; =32
	sub	sp, sp, #16             ; =16
Ltmp13:
	.cfi_def_cfa w29, 16
Ltmp14:
	.cfi_offset w30, -8
Ltmp15:
	.cfi_offset w29, -16
Ltmp16:
	.cfi_offset w19, -24
Ltmp17:
	.cfi_offset w20, -32
Ltmp18:
	.cfi_offset w21, -40
Ltmp19:
	.cfi_offset w22, -48
	mov	 x19, x0
	; InlineAsm Start
	sub	x9, sp, #16, lsl #12    ; =65536
	; InlineAsm End
	movz	x8, #0x20c4, lsl #48
	movk	x8, #0x9ba5, lsl #32
	movk	x8, #0xe353, lsl #16
	movk	x8, #0xf7cf
	movz	w9, #0x3e8
	movn	x10, #0x7777, lsl #16
	movk	x10, #0x8889
	movz	x11, #0x4a90, lsl #48
	movk	x11, #0xbe58, lsl #32
	movk	x11, #0x7de6, lsl #16
	movk	x11, #0xe565
	orr	x12, xzr, #0xaaaaaaaaaaaaaaaa
	movk	x12, #0xaaab
	movk	x12, #0x2aaa, lsl #48
	.loc	1 6 0 prologue_end      ; Util.java:6:0
Ltmp20:
	smulh	x11, x1, x11
	asr	x13, x11, #20
	add	x11, x13, x11, lsr #63
	smulh	x12, x11, x12
	lsr	x13, x12, #63
	lsr	x12, x12, #2
	add	 w12, w12, w13
	orr	w13, wzr, #0x18
	.loc	1 4 0                   ; Util.java:4:0
	smulh	x8, x1, x8
	.loc	1 6 0                   ; Util.java:6:0
	msub	w11, w12, w13, w11
	.loc	1 4 0                   ; Util.java:4:0
	lsr	x12, x8, #63
	asr	x13, x8, #7
	.loc	1 3 0                   ; Util.java:3:0
	add	 w12, w13, w12
	msub	w20, w12, w9, w1
	movz	x9, #0x45e7, lsl #48
	movk	x9, #0xb272, lsl #32
	movk	x9, #0xf608, lsl #16
	movk	x9, #0x770f
	.loc	1 5 0                   ; Util.java:5:0
	smulh	x9, x1, x9
	orr	x12, xzr, #0x8888888888888888
	movk	x12, #0x8889
	.loc	1 4 0                   ; Util.java:4:0
	add	x8, x13, x8, lsr #63
	.loc	1 5 0                   ; Util.java:5:0
	asr	x13, x9, #14
	add	x9, x13, x9, lsr #63
	.loc	1 4 0                   ; Util.java:4:0
	sxtw	x13, w8
	.loc	1 5 0                   ; Util.java:5:0
	smulh	x12, x9, x12
	.loc	1 4 0                   ; Util.java:4:0
	mul	 x10, x13, x10
	.loc	1 5 0                   ; Util.java:5:0
	add	 x12, x12, x9
	lsr	x13, x12, #63
	lsr	x12, x12, #5
	add	 w12, w12, w13
	orr	w13, wzr, #0x3c
	.loc	1 4 0                   ; Util.java:4:0
	lsr	x10, x10, #32
	add	 w10, w10, w8
	.loc	1 5 0                   ; Util.java:5:0
	msub	w12, w12, w13, w9
	.loc	1 4 0                   ; Util.java:4:0
	asr	w9, w10, #5
	add	w10, w9, w10, lsr #31
	; InlineAsm Start
	ldr	 x9, [x9]
	; InlineAsm End
	msub	w8, w10, w13, w8
	.loc	1 5 0                   ; Util.java:5:0
	stp	w12, w8, [sp, #8]
	.loc	1 6 0                   ; Util.java:6:0
	str	w11, [sp, #4]
	.loc	1 8 0                   ; Util.java:8:0
                                        ; kill: X0<def> X19<kill>
	bl	"_[j]java.lang.StringBuilder[allocator][clinit]"
	mov	 x21, x0
	mov	 x0, x19
	mov	 x1, x21
	bl	"_[J]java.lang.StringBuilder.<init>()V"
	mov	 x0, x19
	mov	 x1, x21
	mov	 w2, w20
	bl	"_[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"
	mov	 x20, x0
	ldrb	 wzr, [x20]
	mov	 x0, x19
	bl	"_[j]str__20_00[ldcstring]"
	mov	 x2, x0
	mov	 x0, x19
	mov	 x1, x20
	bl	"_[J]java.lang.StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;"
	mov	 x8, x0
	ldrb	 wzr, [x8]
	ldr	w2, [sp, #12]
	mov	 x0, x19
	mov	 x1, x8
	bl	"_[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"
	mov	 x20, x0
	ldrb	 wzr, [x20]
	mov	 x0, x19
	bl	"_[j]str__20_00[ldcstring]"
	mov	 x2, x0
	mov	 x0, x19
	mov	 x1, x20
	bl	"_[J]java.lang.StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;"
	mov	 x8, x0
	ldrb	 wzr, [x8]
	ldr	w2, [sp, #8]
	mov	 x0, x19
	mov	 x1, x8
	bl	"_[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"
	mov	 x20, x0
	ldrb	 wzr, [x20]
	mov	 x0, x19
	bl	"_[j]str__20_00[ldcstring]"
	mov	 x2, x0
	mov	 x0, x19
	mov	 x1, x20
	bl	"_[J]java.lang.StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;"
	mov	 x8, x0
	ldrb	 wzr, [x8]
	ldr	w2, [sp, #4]
	mov	 x0, x19
	mov	 x1, x8
	bl	"_[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"
	mov	 x8, x0
	ldrb	 wzr, [x8]
	mov	 x0, x19
	mov	 x1, x8
	bl	"_[J]java.lang.StringBuilder.toString()Ljava/lang/String;"
	sub	sp, x29, #32            ; =32
	ldp	x29, x30, [sp, #32]
	ldp	x20, x19, [sp, #16]
	ldp	x22, x21, [sp], #48
	ret
Ltmp21:
Lfunc_end3:
"L_[J]Util.formatTime(JI)Ljava/lang/String;_end":
```

**Comment by badlogic** [comment]
Here's what lldb says when launching the app on the device:

```
Process 230 launched: '/Users/badlogic/workspaces/testWorkspace2/.metadata/.plugins/org.robovm.eclipse.ui/build/issue-966/issue-966/ios/arm64/Sample.app/Sample' (arm64)
Process 230 stopped
* thread #1: tid = 0x2cc7, 0x00000001001dd104 Sample`[J]Util.formatTime(JI)Ljava/lang/String; + 232 at Util.java:4, queue = 'com.apple.main-thread', stop reason = signal SIGSEGV
    frame #0: 0x00000001001dd104 Sample`[J]Util.formatTime(JI)Ljava/lang/String; + 232 at Util.java:4
(lldb) disassemble 
Sample`[J]Util.formatTime(JI)Ljava/lang/String;:
    0x1001dd01c <+0>:   stp    x22, x21, [sp, #-48]!
    0x1001dd020 <+4>:   stp    x20, x19, [sp, #16]
    0x1001dd024 <+8>:   stp    x29, x30, [sp, #32]
    0x1001dd028 <+12>:  add    x29, sp, #32
    0x1001dd02c <+16>:  sub    sp, sp, #16
    0x1001dd030 <+20>:  mov    x19, x0
    0x1001dd034 <+24>:  sub    x9, sp, #16, lsl #12
    0x1001dd038 <+28>:  movz   x8, #0x20c4, lsl #48
    0x1001dd03c <+32>:  movk   x8, #0x9ba5, lsl #32
    0x1001dd040 <+36>:  movk   x8, #0xe353, lsl #16
    0x1001dd044 <+40>:  movk   x8, #0xf7cf
    0x1001dd048 <+44>:  movz   w9, #0x3e8
    0x1001dd04c <+48>:  movn   x10, #0x7777, lsl #16
    0x1001dd050 <+52>:  movk   x10, #0x8889
    0x1001dd054 <+56>:  movz   x11, #0x4a90, lsl #48
    0x1001dd058 <+60>:  movk   x11, #0xbe58, lsl #32
    0x1001dd05c <+64>:  movk   x11, #0x7de6, lsl #16
    0x1001dd060 <+68>:  movk   x11, #0xe565
    0x1001dd064 <+72>:  orr    x12, xzr, #0xaaaaaaaaaaaaaaaa
    0x1001dd068 <+76>:  movk   x12, #0xaaab
    0x1001dd06c <+80>:  movk   x12, #0x2aaa, lsl #48
    0x1001dd070 <+84>:  smulh  x11, x1, x11
    0x1001dd074 <+88>:  asr    x13, x11, #20
    0x1001dd078 <+92>:  add    x11, x13, x11, lsr #63
    0x1001dd07c <+96>:  smulh  x12, x11, x12
    0x1001dd080 <+100>: lsr    x13, x12, #63
    0x1001dd084 <+104>: lsr    x12, x12, #2
    0x1001dd088 <+108>: add    w12, w12, w13
    0x1001dd08c <+112>: orr    w13, wzr, #0x18
    0x1001dd090 <+116>: smulh  x8, x1, x8
    0x1001dd094 <+120>: msub   w11, w12, w13, w11
    0x1001dd098 <+124>: lsr    x12, x8, #63
    0x1001dd09c <+128>: asr    x13, x8, #7
    0x1001dd0a0 <+132>: add    w12, w13, w12
    0x1001dd0a4 <+136>: msub   w20, w12, w9, w1
    0x1001dd0a8 <+140>: movz   x9, #0x45e7, lsl #48
    0x1001dd0ac <+144>: movk   x9, #0xb272, lsl #32
    0x1001dd0b0 <+148>: movk   x9, #0xf608, lsl #16
    0x1001dd0b4 <+152>: movk   x9, #0x770f
    0x1001dd0b8 <+156>: smulh  x9, x1, x9
    0x1001dd0bc <+160>: orr    x12, xzr, #0x8888888888888888
    0x1001dd0c0 <+164>: movk   x12, #0x8889
    0x1001dd0c4 <+168>: add    x8, x13, x8, lsr #63
    0x1001dd0c8 <+172>: asr    x13, x9, #14
    0x1001dd0cc <+176>: add    x9, x13, x9, lsr #63
    0x1001dd0d0 <+180>: sxtw   x13, w8
    0x1001dd0d4 <+184>: smulh  x12, x9, x12
    0x1001dd0d8 <+188>: mul    x10, x13, x10
    0x1001dd0dc <+192>: add    x12, x12, x9
    0x1001dd0e0 <+196>: lsr    x13, x12, #63
    0x1001dd0e4 <+200>: lsr    x12, x12, #5
    0x1001dd0e8 <+204>: add    w12, w12, w13
    0x1001dd0ec <+208>: orr    w13, wzr, #0x3c
    0x1001dd0f0 <+212>: lsr    x10, x10, #32
    0x1001dd0f4 <+216>: add    w10, w10, w8
    0x1001dd0f8 <+220>: msub   w12, w12, w13, w9
    0x1001dd0fc <+224>: asr    w9, w10, #5
    0x1001dd100 <+228>: add    w10, w9, w10, lsr #31
->  0x1001dd104 <+232>: ldr    x9, [x9]
```

Last line prduces the sigseg.

**Comment by badlogic** [comment]
decompiled bitcode:

```llvm
; Function Attrs: noinline nounwind optsize
define %Object* @"[J]Util.formatTime(JI)Ljava/lang/String;"(%Env* %p0, i64 %p1, i32 %p2) #0 {
label0:
  %i3 = alloca i32
  %i4 = alloca i32
  %i5 = alloca i32
  call void asm sideeffect "sub x9, sp, 0x10000", "~{x9},~{dirflag},~{fpsr},~{flags},~{cc}"() #1
  call void asm sideeffect "ldr x9, [x9]", "~{x9},~{dirflag},~{fpsr},~{flags},~{cc}"() #1
  %result1.i = srem i64 %p1, 1000, !dbg !19
  %t4 = trunc i64 %result1.i to i32, !dbg !19
  %result1.i1 = sdiv i64 %p1, 1000, !dbg !21
  %t9 = trunc i64 %result1.i1 to i32, !dbg !21
  %result1.i2 = srem i32 %t9, 60, !dbg !21
  store i32 %result1.i2, i32* %i3, !dbg !21
  %result1.i4 = sdiv i64 %p1, 60000, !dbg !22
  %result1.i8 = srem i64 %result1.i4, 60, !dbg !22
  %t20 = trunc i64 %result1.i8 to i32, !dbg !22
  store i32 %t20, i32* %i4, !dbg !22
  %result1.i9 = sdiv i64 %p1, 3600000, !dbg !23
  %result1.i13 = srem i64 %result1.i9, 24, !dbg !23
  %t28 = trunc i64 %result1.i13 to i32, !dbg !23
  store i32 %t28, i32* %i5, !dbg !23
  %t0.i17 = call %Object* @"[j]java.lang.StringBuilder[allocator][clinit]"(%Env* %p0) #1, !dbg !24
  call void @"[J]java.lang.StringBuilder.<init>()V"(%Env* %p0, %Object* %t0.i17) #1, !dbg !24
  %t0.i18 = call %Object* @"[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"(%Env* %p0, %Object* %t0.i17, i32 %t4) #1, !dbg !24
  %p.i19 = bitcast %Object* %t0.i18 to i8*, !dbg !24
  %i.i20 = load volatile i8* %p.i19, !dbg !24
  %t36 = call %Object* @"[j]str__20_00[ldcstring]"(%Env* %p0), !dbg !24
  %t0.i21 = call %Object* @"[J]java.lang.StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;"(%Env* %p0, %Object* %t0.i18, %Object* %t36) #1, !dbg !24
  %p.i22 = bitcast %Object* %t0.i21 to i8*, !dbg !24
  %i.i23 = load volatile i8* %p.i22, !dbg !24
  %t40 = load i32* %i3, !dbg !24
  %t0.i26 = call %Object* @"[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"(%Env* %p0, %Object* %t0.i21, i32 %t40) #1, !dbg !24
  %p.i24 = bitcast %Object* %t0.i26 to i8*, !dbg !24
  %i.i25 = load volatile i8* %p.i24, !dbg !24
  %t44 = call %Object* @"[j]str__20_00[ldcstring]"(%Env* %p0), !dbg !24
  %t0.i16 = call %Object* @"[J]java.lang.StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;"(%Env* %p0, %Object* %t0.i26, %Object* %t44) #1, !dbg !24
  %p.i14 = bitcast %Object* %t0.i16 to i8*, !dbg !24
  %i.i15 = load volatile i8* %p.i14, !dbg !24
  %t48 = load i32* %i4, !dbg !24
  %t0.i12 = call %Object* @"[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"(%Env* %p0, %Object* %t0.i16, i32 %t48) #1, !dbg !24
  %p.i10 = bitcast %Object* %t0.i12 to i8*, !dbg !24
  %i.i11 = load volatile i8* %p.i10, !dbg !24
  %t52 = call %Object* @"[j]str__20_00[ldcstring]"(%Env* %p0), !dbg !24
  %t0.i7 = call %Object* @"[J]java.lang.StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;"(%Env* %p0, %Object* %t0.i12, %Object* %t52) #1, !dbg !24
  %p.i5 = bitcast %Object* %t0.i7 to i8*, !dbg !24
  %i.i6 = load volatile i8* %p.i5, !dbg !24
  %t56 = load i32* %i5, !dbg !24
  %t0.i3 = call %Object* @"[J]java.lang.StringBuilder.append(I)Ljava/lang/StringBuilder;"(%Env* %p0, %Object* %t0.i7, i32 %t56) #1, !dbg !24
  %p.i = bitcast %Object* %t0.i3 to i8*, !dbg !24
  %i.i = load volatile i8* %p.i, !dbg !24
  %t0.i = call %Object* @"[J]java.lang.StringBuilder.toString()Ljava/lang/String;"(%Env* %p0, %Object* %t0.i3) #1, !dbg !24
  ret %Object* %t0.i, !dbg !24
}
```

The inline assembler is still valid here, seems like the optimizer is getting rid of it.

**Comment by badlogic** [comment]
Debug build has full checkso inline assembler:

```gas
	.globl	"_[J]Util.formatTime(JI)Ljava/lang/String;"
	.align	2
"_[J]Util.formatTime(JI)Ljava/lang/String;": ; @"[J]Util.formatTime(JI)Ljava/lang/String;"
Lfunc_begin22:
	.loc	1 3 0                   ; Util.java:3:0
	.cfi_startproc
; BB#0:                                 ; %label0
	stp	x28, x27, [sp, #-32]!
	stp	x29, x30, [sp, #16]
	add	x29, sp, #16            ; =16
	sub	sp, sp, #416            ; =416
Ltmp42:
	.cfi_def_cfa w29, 16
Ltmp43:
	.cfi_offset w30, -8
Ltmp44:
	.cfi_offset w29, -16
Ltmp45:
	.cfi_offset w27, -24
Ltmp46:
	.cfi_offset w28, -32
	mov	 x8, xzr
	stur	x0, [x29, #-24]
	stur	x8, [x29, #-128]
	stur	x8, [x29, #-136]
	stur	x8, [x29, #-144]
	stur	x8, [x29, #-152]
	stur	x8, [x29, #-160]
	stur	x8, [x29, #-168]
	stur	x8, [x29, #-176]
	stur	x8, [x29, #-184]
	stur	x8, [x29, #-192]
	; InlineAsm Start
	sub	x9, sp, #16, lsl #12    ; =65536
	; InlineAsm End
	; InlineAsm Start
	ldr	 x9, [x9]
	; InlineAsm End
```

So it looks like LLVM removes inline assembler statements when optimizing.

**Comment by badlogic** [comment]
Take a closer look at the release mode assembler code. The two inline assembler statements from `checkso` are actually there. But LLVM seems to have reordered them, putting tons of prologue code in between them.

**Comment by badlogic** [comment]
`checkso` on ARM64 looks like this (from `

```llvm
define private void @checkso() alwaysinline {
  tail call void asm sideeffect "sub x9, sp, 0x10000", "~{x9},~{dirflag},~{fpsr},~{flags},~{cc}"() nounwind
  tail call void asm sideeffect "ldr x9, [x9]", "~{x9},~{dirflag},~{fpsr},~{flags},~{cc}"() nounwind
  ret void
}
```

It appears that LLVM thinks it can treat each inline asm statement as a separate block. Merging the asm into a single statement fixes the issue:

```llvm
define private void @checkso() alwaysinline {
  tail call void asm sideeffect "sub x9, sp, 0x10000; ldr x9, [x9]", "~{x9},~{dirflag},~{fpsr},~{flags},~{cc}"() nounwind
  ret void
}
```

**Comment by ntherning** [comment]
Nice find! I'm quite sure I tried having them in a single statement but never got that to work. Maybe I failed with the syntax.
