### ISSUE TITLE
StringIndexOutOfBoundsException due to empty plist file after running actool

### ISSUE THREAD

**Issue by svenalex** [robovm/robovm#973]
String index out of bounds exception: String index out of range -1

Must have to do with images.xcassets folder. When left out the app launches. Didn't happen in former version. Reproducable with the tabster app.

**Comment by svenalex** [comment]
update: it must have to do with the folder structure.

**Comment by ntherning** [comment]
Was able to reproduce it. There's an empty `.plist` file in the `partial-plists` folder. We should not create that file since it might not actually be written to by `actool`.

```
[DEBUG] /Applications/Xcode.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --platform iphonesimulator --minimum-deployment-target 5.0 --target-device iphone --target-device ipad --compress-pngs --compile /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app /Users/niklas/Projects/robovm-samples/Tabster-no-ib/resources/Images.xcassets
[DEBUG] /* com.apple.actool.compilation-results */
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/cherrylake.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/cherrylake@2x.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/lakedonpedro.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/lakedonpedro@2x.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/left.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/left@2x.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/left_pressed.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/left_pressed@2x.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab1.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab1@2x.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab2.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab2@2x.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab3.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab3@2x.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab4.png
[DEBUG] /Users/niklas/Projects/robovm-samples/Tabster-no-ib/target/robovm.tmp/Tabster.app/tab4@2x.png
[DEBUG]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.240 s
[INFO] Finished at: 2015-05-07T10:38:49+02:00
[INFO] Final Memory: 45M/471M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.robovm:robovm-maven-plugin:1.2.0:iphone-sim (default-cli) on project robovm-samples-tabster-no-ib: Failed to launch IOS Simulator: java.lang.StringIndexOutOfBoundsException: String index out of range: -1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.robovm:robovm-maven-plugin:1.2.0:iphone-sim (default-cli) on project robovm-samples-tabster-no-ib: Failed to launch IOS Simulator
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to launch IOS Simulator
	at org.robovm.maven.plugin.AbstractIOSSimulatorMojo.execute(AbstractIOSSimulatorMojo.java:71)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.robovm.compiler.CompilerException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.robovm.compiler.target.ios.IOSTarget.createInfoPList(IOSTarget.java:722)
	at org.robovm.compiler.target.ios.IOSTarget.prepareLaunch(IOSTarget.java:374)
	at org.robovm.compiler.target.ios.IOSTarget.doLaunch(IOSTarget.java:496)
	at org.robovm.compiler.target.AbstractTarget.launch(AbstractTarget.java:280)
	at org.robovm.compiler.AppCompiler.launchAsync(AppCompiler.java:714)
	at org.robovm.compiler.AppCompiler.launch(AppCompiler.java:699)
	at org.robovm.compiler.AppCompiler.launch(AppCompiler.java:694)
	at org.robovm.maven.plugin.AbstractIOSSimulatorMojo.execute(AbstractIOSSimulatorMojo.java:68)
	... 21 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.checkBounds(String.java:369)
	at java.lang.String.<init>(String.java:533)
	at com.dd.plist.PropertyListParser.determineType(PropertyListParser.java:125)
	at com.dd.plist.PropertyListParser.parse(PropertyListParser.java:181)
	at org.robovm.compiler.target.ios.IOSTarget.createInfoPList(IOSTarget.java:719)
	... 28 more
```
