### ISSUE TITLE
ABAddressBook.getAllPeople 

### ISSUE THREAD

**Issue by btukacs** [robovm/robovm#984]
Hy!

I get the following error if i call ABAddressBook.getAllPeople.
Before with previous robovm 1.1.0 version i didn’t get this error.

java.lang.InstantiationException: 
	at org.robovm.rt.VM.allocateObject(Native Method)
	at org.robovm.rt.bro.NativeObject$Marshaler.toObject(NativeObject.java:88)
	at org.robovm.apple.corefoundation.CFType$Marshaler.toObject(CFType.java:68)
	at org.robovm.apple.corefoundation.CFType$Marshaler.toObject(CFType.java:51)
	at org.robovm.apple.addressbook.ABPerson$AsListMarshaler.toObject(ABPerson.java:43)
	at org.robovm.apple.addressbook.ABAddressBook.getAllPeople(Native Method)

**Comment by btukacs** [comment]
1.2.1 snapshot fixed it
