### ISSUE TITLE
Snapshot distribution JAR broken (?)

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#986]
Compiling an app via Gradle (all caches cleared, etc.):

```
Caused by: : Error while expanding /Users/badlogic/.m2/repository/org/robovm/robovm-dist/1.2.1-SNAPSHOT/robovm-dist-1.2.1-SNAPSHOT-nocompiler.tar.gz
java.io.IOException: Error detected parsing the header
	at org.apache.tools.ant.taskdefs.Untar.expandFile(Untar.java:116)
	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:132)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:77)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:92)
	at org.robovm.gradle.tasks.AbstractRoboVMTask.unpack(AbstractRoboVMTask.java:241)
	at org.robovm.gradle.tasks.AbstractRoboVMTask.configure(AbstractRoboVMTask.java:160)
	at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:87)
	at org.robovm.gradle.tasks.AbstractIOSSimulatorTask.launch(AbstractIOSSimulatorTask.java:37)
	... 58 more
Caused by: java.io.IOException: Error detected parsing the header
	at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:292)
	at org.apache.tools.ant.taskdefs.Untar.expandStream(Untar.java:165)
	at org.apache.tools.ant.taskdefs.Untar.expandFile(Untar.java:114)
	... 67 more
Caused by: java.lang.IllegalArgumentException: Invalid byte 32 at offset 7 in '       {NUL}' len=8
	at org.apache.tools.tar.TarUtils.parseOctal(TarUtils.java:134)
	at org.apache.tools.tar.TarUtils.parseOctalOrBinary(TarUtils.java:172)
	at org.apache.tools.tar.TarEntry.parseTarHeader(TarEntry.java:912)
	at org.apache.tools.tar.TarEntry.parseTarHeader(TarEntry.java:899)
	at org.apache.tools.tar.TarEntry.<init>(TarEntry.java:323)
	at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:290)
	... 69 more
```

**Comment by badlogic** [comment]
Untaring via `tar xzf` works as intended :/

**Comment by badlogic** [comment]
Gradle specific issue, closing this in favour of https://github.com/robovm/robovm-gradle-plugin/issues/43
