### ISSUE TITLE
@Method / @Property don't need to be available at runtime

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm#989]
We never use them at runtime. Only the `ObjCMemberPlugin` looks at them at compile time. Shaves off a little from executables.

**Comment by BlueRiverInteractive** [comment]
When changing the retention policy of these annotations to either SOURCE or CLASS, the app will fail when accessing a native `@Method` or `@Property` method with an `UnsatisfiedLinkError`:

``` Java
java.lang.UnsatisfiedLinkError: org.robovm.apple.uikit.UIApplication.getDelegate()Lorg/robovm/apple/uikit/UIApplicationDelegate;
    at org.robovm.apple.uikit.UIApplication.getDelegate(Native Method)
    at org.robovm.test.Test.didFinishLaunching(Test.java:33)
    at org.robovm.test.Test.$cb$application$didFinishLaunchingWithOptions$(Test.java)
    at org.robovm.apple.uikit.UIApplication.main(Native Method)
    at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:395)
    at org.robovm.test.Test.main(Test.java:51)
```
