### ISSUE TITLE
New Plugin crashes intellij idea

### ISSUE THREAD

**Issue by douglaslyon** [robovm/robovm#997]
Hi All,
On the mac, a new plugin release from 5/28/15 causes a crash of intellij idea 14 on a mac.
please see the detailed report, below.
Thanks!
 - Doug
Plugin 'org.robovm.intellij' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

com.intellij.diagnostic.PluginException: org/robovm/idea/components/RoboVmApplicationComponent : Unsupported major.minor version 51.0 [Plugin: org.robovm.intellij]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: org/robovm/idea/components/RoboVmApplicationComponent : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 30 more

**Comment by badlogic** [comment]
Please make sure to run IDEA with Java 7+ as outlined in this doc
http://docs.robovm.com/getting-started/intellij.html

**Comment by douglaslyon** [comment]
Hi Mario,
According to the "Java Control Panel"
"Your system has the recommended version of Java."
Java 7 Update 75.
This is confirmed in the Java Runtime Environment Settings.

Where do we specify which Java to run Intellij IDEA with?
Can you recompile with the older bytecodes being emitted to enable
compatibility?
I think it is just a compiler switch...right?

Thanks!
  - Doug

**Comment by badlogic** [comment]
Please follow the instructions i linked you to earlier. You need to modify
the Info.plist file of IntelliJ IDEA.

I'm afraid we can't recompile the plugin as we use Java 7 language features
and APIs.

**Comment by douglaslyon** [comment]
Hi Mario,
Getting a different error now...please see below.
I think I may be using the wrong "get started" instructions,
as these are for eclipse, and I am on intellij idea...
Using:
http://robovm.com/support/documentation/
I never get to the pasting of the sample code in as:
/Users/lyon/IdeaProjects/IOSDemo/build.gradle
Error:(12, 0) Cause: org/robovm/gradle/RoboVMPlugin : Unsupported 
major.minor version 51.0

Info.plist says:
"    <key>JVMVersion</key>
       <string>1.7+</string>
"
Thanks for your time (I know, these are newbee questions!).
  - Doug

**Comment by douglaslyon** [comment]
Hi Mario,
Made a little more progress; now I get:
Information:Using javac 1.7.0_71 to compile java sources
Information:java: Errors occurred while compiling module 'untitled1'
Information:5/31/15, 2:36 AM - Compilation completed with 1 error and 0 
warnings in 563ms
Error:java: invalid source release: 8
using:
http://docs.robovm.com/getting-started/intellij.html

I do not have a product key...could that be the problem?

Any ideas?
Thanks!
  - Doug

more idea.vmoptions
-Xms128m
-Xmx1G
-XX:MaxPermSize=350m
-XX:ReservedCodeCacheSize=225m
-XX:+UseCompressedOops

**Comment by badlogic** [comment]
Hi,

I assume you created a default single view app? That uses storyboards,
formehich you need at least a trial key.

**Comment by douglaslyon** [comment]
Hi Mario,
That makes sense.
I used a trial key;
P9D8-JQRK-SG9I-PVHM-JZ55-M4BU-TITA

That is good enough, for now, right?

I have an account.
The instructions say: "RoboVM IOS App without Storyboards"
That is what I used.

Was I supposed to use RoboVM IOS Single View App (With storyboards)?
http://docs.robovm.com/getting-started/intellij.html
Thanks!
  - Doug

TRIAL

1 developers
Expires: Jun 11, 2015
Active licenses: 1 of 1
How

**Comment by badlogic** [comment]
Yeah, that's correct then when following the guide. Did you install Xcode?
If so, open it up and make sure you Ok'ed all dialogues that pop up. Also
make sure the command line tools are installed. Go to Xcode -> Preferences
-> Downloads and you should see them. If not ask Xcode to install them.
There might also be a dialogue asking you to accept the Xcode Terms of
Service.

**Comment by douglaslyon** [comment]
Hi Mario,
Command line tools...good idea!
This is what I did:
xcode-select --install

However, they do not show in the Downloads dialog of Preferences in 
Xcode (even after
a restart). Only the simulator for 7.1 shows.

Is this version issue?

I am running 6.1 of xcode on macosx 10.9....

Thanks!
- Doug

**Comment by badlogic** [comment]
Hm, that might be the issue. When you open IDEA and compile, there's a
button called RoboVM at the bottom of IDEA. When you click that after
trying to compile the app, you'll get more information on what failed.
Could you post that here?

As for Xcode, 6.1 on OS X 10.9 should be fine. I suspect the command line
tools aren't in place. You could create a project in Xcode and compile that
to so if somethings wrong there.

**Comment by douglaslyon** [comment]
Hi Mario,
The robovm console says:
[INFO] Stopping all Interface Builder integrator daemons
[INFO] Stopping all Interface Builder integrator daemons
[INFO] Project created in /Users/lyon/IdeaProjects/untitled1
[INFO] Starting Interface Builder integrator daemon for module untitled1
[INFO] Created new Xcode project untitled1
[INFO] RoboVM plugin initialized
[ERROR] Can't compile application due to previous compilation errors
[ERROR] Can't compile application due to previous compilation errors
[ERROR] Can't compile application due to previous compilation errors
[ERROR] Can't compile application due to previous compilation errors
[ERROR] Can't compile application due to previous compilation errors

The Messages from Make say:
Information:Using javac 1.7.0_71 to compile java sources
Information:java: Errors occurred while compiling module 'untitled1'
Information:5/31/15, 3:11 AM - Compilation completed with 1 error and 0 
warnings in 488ms
Error:java: invalid source release: 8

You write:
"I suspect the command line
tools aren't in place."
Could be you are correct.
However,
which gcc
/usr/bin/gcc
which make
/usr/bin/make
xcode-select -p
/Applications/Xcode.app/Contents/Developer
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 6.2.0.0.1.1424975374
volume: /
location: /
install-time: 1433057545
groups: com.apple.FindSystemFiles.pkg-group 
com.apple.DevToolsBoth.pkg-group 
com.apple.DevToolsNonRelocatableShared.pkg-group

Not sure why they Command Line tools don't show up in the xcode download....
that is odd.

Configuration is really hard!

Do I need jdk8 to make this work?
Thanks!
  - Doug

**Comment by badlogic** [comment]
> Error:java: invalid source release: 8

This sure looks like IDEA is trying to compile the code in Java 8 mode. Go
to File -> Project Structure. On the left hand side you can select Project
and Modules. Check for both which Java language level is set. If it's set
to 8, but you only have JDK 7 installed, set it to 7 instead.

Sorry for the inconvenience, setup is usually quite straight forward. We'll
take your feedback and see how we can improve things!

**Comment by douglaslyon** [comment]
Hi Mario,
In file:Project Structure
the language level is set at 6 - @Override in interfaces
the sdk is 1.7

I sure don't have jdk8 installed...
clicking around randomly, I found modules language level is 8 - lambdas, 
type annotations,
etc!
I switched that to 7 - Diamonds, ARM,...
Now it works!

Thanks very much for your help.
Regards,
  - Doug

**Comment by badlogic** [comment]
Great, could you close this issue and file an issue with
https://github.com/robovm/robovm-idea/issues? We should detect the language
level supported by the installed JDKs.

Thanks for all the feedback. We'll try to make things easier for newcomers!

**Comment by douglaslyon** [comment]
Hi Mario,
How do I close the issue?
I went to the github address, below, but the issue was not
easy to find.
Thanks!
  - Doug

**Comment by douglaslyon** [comment]
Sorry for being dense...I found the close issue button at the bottom of this page!

**Comment by badlogic** [comment]
No problem :)

I setup an issue on the IDEA plugin tracker here: https://github.com/robovm/robovm-idea/issues/67

**Comment by douglaslyon** [comment]
Hi Mario,
Do you know if someone has ported the compass example
to RoboVM?
I saw:
" The compass is currently not available on iOS devices since there is 
no implementation in the RoboVM - backend yet."
https://github.com/libgdx/libgdx/wiki/Compass
That was from:
Sep 13, 2014

Perhaps something has come up, since then.

I am keen on seeing if someone has implemented a real-time
pointer (either based on the magnetic sensor, or location
services, or both).

Thanks!
  - Doug
